### ISSUE TITLE
Add hyperlink to pub badge

### ISSUE THREAD

**Issue by PlugFox** [felangel/mason#1]
Add hyperlink to pub badge

`[![Pub](https://img.shields.io/pub/v/mason.svg)](https://pub.dev/packages/mason)`
[![Pub](https://img.shields.io/pub/v/mason.svg)](https://pub.dev/packages/mason)

**Comment by felangel** [comment]
Hey @PlugFox 👋 
Thanks for opening an issue!

I added the links as part of https://github.com/felangel/mason/commit/d02c60e963e13eb6d3c4e89c52b8d064c6a710d2 🎉
