### ISSUE TITLE
How to preserve styles when running in a Process

### ISSUE THREAD

**Issue by matthew-carroll** [felangel/mason#1005]
I'm running a Dart script in a `Process` from another Dart script:

```dart
final result = await Process.run(
  'dart',
  [executableFile.path],
);
stdout.write(result.stdout);
stderr.write(result.stderr);
```

The Dart script that I'm running in the `Process` uses `mason_logger` for output. Normally, that output looks as expected. However, once I forward `stdout` and `stderr` to the main process, it loses all styles.

Is there a way to preserve styles when forwarding the output like this?

**Comment by felangel** [comment]
Hi @matthew-carroll 👋 
You can achieve this by using `ProcessStartMode.inheritStdio`:

**main.dart**
```dart
import 'dart:io';

void main() async {
  final process = await Process.start(
    'dart',
    ['foo.dart'],
    mode: ProcessStartMode.inheritStdio,
  );
  final exitCode = await process.exitCode;
  print('exit $exitCode');
}
```

**foo.dart**
```dart
import 'package:mason_logger/mason_logger.dart';

void main() {
  Logger().warn('warning');
}
```

Hope that helps 👍

**Comment by matthew-carroll** [comment]
Looks like that worked. Thanks.
