### ISSUE TITLE
docs: Unsure of what the bundle command does.

### ISSUE THREAD

**Issue by ajilo297** [felangel/mason#104]
**Description**

From the documentation and CLI help, I can understand what the `bundle` command does. But how do I use it?  Can I create a brick from a bundle? Can you provide a usage example for the bundled output?

**Requirements**

- [x] Provide usage example of bundled output.

**Comment by felangel** [comment]
Hi @ajilo297 👋 
Thanks for opening an issue!

Sorry for the inconvenience but yes you can create a `MasonGenerator` from a bundle which comes in handy if you're making your own custom CLI. You can take a look at [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli/blob/bfc532e4e4cb3d77285b39540f9dff1e7e72dc11/lib/src/commands/create.dart#L39) for an example. I'll keep this open to improve the docs 👍

**Comment by ajilo297** [comment]
@felangel No incovenience at all. Was curious about how to use it. Figured it out from the [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli/blob/bfc532e4e4cb3d77285b39540f9dff1e7e72dc11/lib/src/commands/create.dart#L39) example. Thanks
