### ISSUE TITLE
fix: cannot ctrl+C when `chooseOne` menu is shown

### ISSUE THREAD

**Issue by bryanoltman** [felangel/mason#1090]
**Description**

When a list of radio buttons is shown with `chooseOne`, it is not possible to terminate the command using ctrl+C

**Steps To Reproduce**

1. Run `shorebird preview` with more than one app
2. Type ctrl+C

**Expected Behavior**

The shorebird command exits and I see my terminal prompt

**Comment by Luckey-Elijah** [comment]
I can verify it also happens for `chooseAny`.

**Comment by Luckey-Elijah** [comment]
I could publish a fix before then if needed - just let me know!

**Comment by felangel** [comment]
> I could publish a fix before then if needed - just let me know!

If you have time to open a PR feel free, thanks! 🙏
