### ISSUE TITLE
feat: Extract mason_logger

### ISSUE THREAD

**Issue by feinstein** [felangel/mason#1170]
I find mason_logger very useful for CLIs in general, and I totally know I am nitpicking, but I think it would be nice if the library was not tied to mason. If not to be extracted from the repo, then change it's name to `cli_logger` or submit a PR to `cli_utils` and merge both libs?

I just feel it's weird to add `mason_logger` into my CLIs, even though I am not using mason at all in the project.

**Comment by felangel** [comment]
Hi @feinstein 👋 
Thanks for opening an issue!

The library isn't really tied to mason, it's just part of the mason ecosystem hence the mason prefix. If you want you can always create your own library and re-export `package:mason_logger` to avoid having to add `package:mason_logger` to your CLIs:

```dart
library my_cool_logger;

export 'package:mason_logger/mason_logger.dart';
```

```dart
import 'package:my_cool_logger/my_cool_logger.dart';

void main() {
  final logger = Logger();
}
```

Does that help?

**Comment by feinstein** [comment]
As I said, I might be nitpicking, nothing big, thanks for the attention.
