### ISSUE TITLE
feat: Possibility to add multiple files dynamically

### ISSUE THREAD

**Issue by ajilo297** [felangel/mason#118]
**Description**

I was wondering if it would be possible to add a feature wherein we can generate files dynamically if provided as an array. This would be very useful when using mason to generate a bunch of documentation files for example.

``` 
// config.json

{
    "page_info": [
        {
            "name": "Intro"
        },
        {
            "name": "Getting Started"
        },
        {
            "name": "FAQ"
        }
    ]
}
```

It would have been great if we can create a brick template like this under `__brick__`
```
{{#page_info}}{{name}}.md{{/page_info}}
```

and it should be able to generate like this

```
- out
| -- Intro.md
| -- Getting Started.md
| -- FAQ.md
```

**Comment by felangel** [comment]
Hi @ajilo297 👋
Thanks for opening an issue.

This is already supported — you can take a look at the [todos example](https://github.com/felangel/mason/tree/master/bricks/todos). Hope that helps!
