### ISSUE TITLE
chore: `mason_logger` - update win32 package

### ISSUE THREAD

**Issue by jifferon** [felangel/mason#1248]
**Description**

If there's both `dcli` and `mason_logger` dependencies in a `pubspec.yaml`:

```yaml
dependencies:
  mason_logger: ^0.2.11
  dcli: ^3.3.5
```

Then `dart pub get` would fail with following message:

```
Because dcli >=3.1.0 depends on win32 ^4.1.4 and mason_logger 0.2.11 depends on win32 ^5.0.7, dcli >=3.1.0 is incompatible with mason_logger 0.2.11.
And because no versions of mason_logger match >0.2.11 <0.3.0, dcli >=3.1.0 is incompatible with mason_logger ^0.2.11.
So, because cli_fun depends on both mason_logger ^0.2.11 and dcli ^3.3.5, version solving failed.
```

Please consider updating to a new version on `win32` to make it work.

**Requirements**

- [x] No functional changes to the code

**Comment by felangel** [comment]
Based on the error it looks like dcli needs to update, not mason_logger.

**Comment by felangel** [comment]
Closing this as `mason_logger` supports the latest version of `package:win32`
