### ISSUE TITLE
Failing to activate mason_cli after upgrading to mason_cli: ^0.1.0-dev.54

### ISSUE THREAD

**Issue by naveenr-egov** [felangel/mason#1297]
**Description**

Error while running dart pub global activate mason_cli

**Steps To Reproduce**

Flutter version: 3.16.5

if mason_cli is updated to mason_cli: ^0.1.0-dev.54 it refers to mason_logger: ^0.2.13 which has removed depricated windows methods

**Expected Behavior**

should activate mason

**Screenshots**

![Screenshot from 2024-04-19 14-31-11](https://github.com/felangel/mason/assets/154230258/62b22302-da24-488b-9aaf-34fdeeb65252)

**Comment by nsiangxuan98cyneox** [comment]
#[0.1.0-dev.51](https://pub.dev/packages/mason/versions/0.1.0-dev.51)
