### ISSUE TITLE
feat: set default output directory 

### ISSUE THREAD

**Issue by PeterJ504** [felangel/mason#1308]
**Description**

I have a block that I always want created in the same directory.  I can use the -o option but it gets tedious as the directory path is long and constant.  Is there a way to default the brick output directory to something else.

Perhaps adding a tag in the mason.yaml file would work.

**Comment by felangel** [comment]
Hi @PeterJ504 👋 
Thanks for opening an issue!

Can you provide a bit more context (for example what brick you're using and the full `mason` command you're running)?

**Comment by PeterJ504** [comment]
Sure.  Let's say I have my own global brick called project.  I want all projects to create a subdirectory in the same root directory.
Currently, to make a new project I type `mason make project -o c:\Users\Robert\OneDrive\Coding\flutter\projects`
Since all projects go into the same folder, I'd like to be able to default the output directory so that I don't have to always type the long location name.
One solution would be to add a line in the brick's mason.yaml file.  Something like:
default_dir: c:\Users\Robert\OneDrive\Coding\flutter\projects
Then when I run make again, if I don't specify the -o option, it will go in the default output directory instead of the current directory.

**Comment by felangel** [comment]
@PeterJ504 since this is a per-machine/user configuration I recommend just creating a bash alias. Happy to revisit this if you or others feel strongly about it, thanks!
