### ISSUE TITLE
fix: mason update doesn't reach last version

### ISSUE THREAD

**Issue by B0berman** [felangel/mason#1389]
**Description**

When doing a `mason update` I get a success prompt `Updated to 0.1.0-dev.55` but if I execute a `mason --version` after that, I am still on the `0.1.0-dev.53`

**Expected Behavior**

`mason update` should update to the last available version

**Screenshots**

```
User - Dev % mason update
✓ Checked for updates (94ms)
✓ Updated to 0.1.0-dev.55 (0.8s)
User - Dev % mason --version
0.1.0-dev.53

Update available! 0.1.0-dev.53 → 0.1.0-dev.55
Changelog: https://github.com/felangel/mason/releases/tag/mason_cli-v0.1.0-dev.55
Run mason update to update
```

**Comment by felangel** [comment]
Hi @B0berman 👋 
Thanks for filing an issue! Does deactivating and reactivating resolve the correct version?
```
dart pub global deactivate mason_cli
dart pub global activate mason_cli
```

Also can you share the version of Dart? (`dart --version`)

**Comment by B0berman** [comment]
After deactivating and reactivating, `mason --version` still shows that I'm using .53 and that .55 is available.
What's interesting though is that deactivating prompted `Deactivated package mason_cli 0.1.0-dev.55.`

I was using Dart 3.4.4 but same behaviour after updating to 3.5

**Comment by felangel** [comment]
Seems like maybe you have multiple mason installations? Can you clear your pub cache and also ensure you haven't installed mason via `brew` and try again?

**Comment by B0berman** [comment]
I had indeed mason downloaded from brew, I removed it and reinstalled it from pub.dev and now it's working 👍 

Thanks a lot!

**Comment by B0berman** [comment]
CLosing since it's solved
