### ISSUE TITLE
issue: Pub.dev labels any packages using it as Windows-only

### ISSUE THREAD

**Issue by rezmeplxrf** [felangel/mason#1420]
I understand this works on other OSs, but Pub.dev labels any packages using it as Windows-only. Is there a way to resolve this?

**Comment by felangel** [comment]
This is fixed in https://github.com/felangel/mason/commit/694619c5962b7a953ba680d329fb6cae3a98e9c5 and I'll publish a new release shortly which should reflect in pub.dev, thanks!

**Comment by rezmeplxrf** [comment]
> This is fixed in [694619c](https://github.com/felangel/mason/commit/694619c5962b7a953ba680d329fb6cae3a98e9c5) and I'll publish a new release shortly which should reflect in pub.dev, thanks!

Thank you for the quick fix and the package!
