### ISSUE TITLE
feat: Allow login in CI systems (non-interactive shell)

### ISSUE THREAD

**Issue by Peetee06** [felangel/mason#1426]
**Description**

In order to continuously publish mason bricks I would like to be able to login to mason in a non-interactive shell.  
I've tried:  
- piping email and password but am receiving `StdinException: Error setting terminal line mode, OS Error: Inappropriate ioctl for device, errno = 25`.
- `mason login --email test --password test` which has no effect and asks for the email and password anyways

Allowing to pass the email and password as arguments would do the trick.

I'd be happy to contribute myself :)

**Comment by felangel** [comment]
Hi @Peetee06 👋 

You can login on your machine and upload your credentials to a secret manager which you then use in ci. See https://workflows.vgv.dev/docs/workflows/mason_publish for an example.

**Comment by felangel** [comment]
> @felangel awesome, I'll try the VGV workflow! Thank you very much! 🦾

No problem! Closing this for now but feel free to comment if you have any trouble and I’m happy to help!
