### ISSUE TITLE
chore: promote to stable

### ISSUE THREAD

**Issue by timcreatedit** [felangel/mason#1432]
**Description**
Thank you for this amazing work! I was wondering when you're planning to promote mason from a pre-release to a stable `0.1.0` version. I tried to look for documentation on this, or Milestones on GitHub etc., but couldn't find anything.

We are relying on mason with our `figmage` package to generate an empty dart package before running code generation. However, since `mason` is still a pre-release, pub prevents us from promoting `figmage` to stable.

**Requirements**

- [X] No functional changes to the code

**Comment by felangel** [comment]
Hey 👋 
Thanks so much for opening an issue and for the kind words. I've been mainly holding off on releasing a stable release until https://github.com/felangel/mason/issues/215 was addressed but happy to cut a `0.1.0` version if it'll unblock your team.

**Comment by timcreatedit** [comment]
Hi, thanks for the answer :) Through the other issue, I just found #891, sorry that I missed that somehow 🥲

#215 sounds super cool, and I see why you would want to wait for it. I'll leave it up to you of course, but I also feel like since it's been almost 3 years, and we're in 0.x territory still, it might be fine if it's part of an upcoming major release?
