### ISSUE TITLE
refactor: --version should clearly say it is version of mason_cli

### ISSUE THREAD

**Issue by Take-A-Byte** [felangel/mason#1478]
**Description**

When I was trying to use the ui_package brick, I kept getting the following error:
```
The current mason version is 0.1.0.
Because ui_package requires mason version >=0.1.0-dev.42 <0.1.0, version solving failed.
```

But when I did `mason --version` it showed `0.1.0-dev.56`.

I was under the assumption that the CLI version would correspond to mason package version or that it would be the mason package version itself. Looking back, I realize this was a poor assumption.

But I wonder if other new developers would face the same issue and spend a day chasing their tails.

Could we do something about this? I can think of the following and I would love to update the code based on our discussion here:
1. Use a clearer executable name like `mason_cli` instead of `mason`. This way, running `mason_cli --version` makes it clear we’re referencing the CLI.
2. Specify the version as `mason_cli - 0.1.0-dev.56` instead of just `0.1.0-dev.56`

**Requirements**

- [ ] There is no drop in test coverage.

**Comment by gotecq-linhdoan** [comment]
@Take-A-Byte can i ask how you can fix that error?
I keep facing that error even when i had run 
`dart pub global activate mason_cli 0.1.0-dev.57`
```
mason --version
0.1.0-dev.57
```

**Comment by Take-A-Byte** [comment]
@gotecq-linhdoan The version you get with mason --version is the version of mason-cli.
However, the version you should be looking for is the mason package, which is a dependency of mason_cli.

You can find the version of mason being used in the [pubspec.yaml](https://github.com/felangel/mason/blob/master/packages/mason_cli/pubspec.yaml) file.

I believe you can find the mason version when you activate mason_cli in the logs as well (not 100% sure though - but if not, the above pubspec.yaml file should have your answer)

**Comment by felangel** [comment]
This should be improved in v0.1.2 of mason_cli 🎉

**Comment by Take-A-Byte** [comment]
Thank you @felangel 🙇
