### ISSUE TITLE
feat: show correct msg when there is no mason.yam.

### ISSUE THREAD

**Issue by huang12zheng** [felangel/mason#158]
**Description**

* Clearly describe what you are looking to add. The more context the better.

1. there is no mason.yaml, and no use `mason add -g`
2. `mason add` show a bad err message.
```sh
# output
mason add '/Users/huangzheng/very_good_cli/example/vscode_dart_extension/bricks/groovin_core' 
brick not found at path /Users/huangzheng/very_good_cli/example/vscode_dart_extension/bricks/groovin_core
```
---
3. ref code
```dart
final bricksJson = isGlobal ? globalBricksJson : localBricksJson;
    if (bricksJson == null) {
      throw UsageException('brick not found at path $location', usage);
...
Directory? get __entryPoint {
    try {
      return entryPoint;
    } catch (_) {} // <<<<<<<<<<<<<
    return null;  // <<<<<<<<<<<<<
  }
...
Directory get entryPoint {
    if (_entryPoint != null) return _entryPoint!;
    final nearestMasonYaml = MasonYaml.findNearest(cwd);
    if (nearestMasonYaml == null ||
        nearestMasonYaml.parent.path == BricksJson.globalDir.path) {
      throw const MasonYamlNotFoundException();
    }
    return _entryPoint = nearestMasonYaml.parent;
  }
```

**Requirements**

- [ ] show `mason.yaml not found` rather than `brick not found`
- [ ] or show use `-g` to add to global path
- [x] if there is no brick, it would still be ok.

**Comment by felangel** [comment]
Hi @huang12zheng 👋 
Thanks for opening an issue!

This is working as expected because mason add requires a path to a brick not a mason.yaml. You cannot `mason add` a using a `mason.yaml` and must instead pass the path to the brick (directory where the `brick.yaml` exists).

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by huang12zheng** [comment]
* some instructions about issue
Through, It's been a problem for a long time.
I think I said 'Mason add '/Users/huangzheng/very_good_cli/example/vscode_dart_extension/bricks/groovin_core''
It has brick paths.

> So we're not talking about the same thing

* more instructions about why bug
error due to cli can't find mason.yaml, rathor than brick.yaml.
But it tall me, there is no bric

> But I don't know if that's still for now, because this is a boundary case, and I did not pay attention to this issue
