### ISSUE TITLE
fix: Create template brick filename on Windows

### ISSUE THREAD

**Issue by ltropin** [felangel/mason#165]
**Description**
I have problem with creating template file on Windows

**Steps To Reproduce**

I working in VSCode in Windows and I did next actions:
1. Create file with name `{{#snakeCase}}{{variable}}{{/snakeCase}}_bloc.dart`
2. Press Enter
3. I got directory  `{{#snakeCase}}{{variable}}{{` with file attached inside `snakeCase}}_bloc.dart`

**Expected Behavior**
Created file `{{#snakeCase}}{{variable}}{{/snakeCase}}_bloc.dart`

**Screenshots**
![image](https://user-images.githubusercontent.com/43740557/145732750-fb6b67fa-5781-490c-9e04-f5bea7a5adff.png)

**Additional Context**
I think it's problem with them that Windows think `/` is part of path and he creating folder with file)

**Comment by felangel** [comment]
Hi @ltropin 👋
Thanks for opening an issue!

I believe this is working as expected (see #36). Running mason make should generate the expected output even though the slashes are treated as nested directories.

Let me know if that helps 👍

**Comment by ltropin** [comment]
@felangel Wow, Windows creates a directory, but mason still recognizes it as a file and creates it using a template. Only it doesn't look very nice.
