### ISSUE TITLE
feat: a way to ignore certain files/paths in a brick

### ISSUE THREAD

**Issue by orenwang** [felangel/mason#166]
**Description**

Hi, I wonder is there any way currently to ignore certains files/paths inside a brick?

**Additional Context**

For example, when I include some `*.lock` file inside a brick, obviously that `*.lock` file should not be included in the bundle. 

Thank you for this amazing work!

**Comment by felangel** [comment]
Hi @orenwang 👋 
Thanks for opening an issue!

Can you provide a bit more context? Why are you including the *.lock file in the brick if you don't want it to be included in the bundle? Thanks!

**Comment by orenwang** [comment]
Oh yeah... I may have made some (possibly unusual 🤔) assumptions:
1. My brick is executable, so I would simpy run the main.dart inside the brick, which brings *.lock file and build/.dart_tool directories.
OR
2. My brick is a standalone repository, which contains .git/.vscode directories.

If you don't think these are common cases, the issue can be closed for sure.

**Comment by orenwang** [comment]
Also, I've made changes in my own fork and a PR (https://github.com/felangel/mason/pull/167) here. But feel free to close it if you feel it's not necessary.

**Comment by felangel** [comment]
> Oh yeah... I may have made some (possibly unusual 🤔) assumptions:
> 
> If you don't think these are common cases, the issue can be closed for sure.

Thanks for the additional details:

> 1. My brick is executable, so I would simpy run the main.dart inside the brick, which brings *.lock file and build/.dart_tool directories.

Why are you running the `main.dart` within the `brick`? The `brick` should only be used to store the templated code. I would recommend using `mason make` to generate code from the `brick` and then executing the generated code.

> 2. My brick is a standalone repository, which contains .git/.vscode directories.

I highly recommend taking a look at how the bricks are structured at https://github.com/felangel/mason/tree/master/bricks. You can have a `.git` at the root (outside of any `__brick__` folders) and if you don't want .vscode to be generated then I'd recommend removing it from the `__brick__` directory.

Hope that helps 👍

**Comment by orenwang** [comment]
Yeah I realize the way I use it is a bit wierd. Thanks for helping!
