### ISSUE TITLE
feat: Aliases for variables

### ISSUE THREAD

**Issue by Chojecki** [felangel/mason#183]
Great package. Thanks!

**Description**

Would be nice to have aliases for variables like:

`snake_name` =  `{{#snakeCase}}{{name}}{{/snakeCase}}` 
`camelName` =  `{{#camelCase}}{{name}}{{/camelCase}}`
`PascalName` =  `{{#pascalCase}}{{name}}{{/pascalCase}}`

Sometimes I'm using the same variable in a lot of places like class where Im importing `snake_name` and using `PascalName` as class name etc. and because of that the file readability isn't perfect. What's more it could help with VSCode file naming where `/` character will create a folder like `{{#snakeCase}}{{name}}{{` / `snakeCase}}.dart`

**Comment by alestiago** [comment]
I think this could be very useful and interesting to play with. What implementations do we have in mind?

I can think of having a file preamble (similar to LaTeX) where one defines the constants could be a possible implementation. Or alternatively having some syntax that allows declaring variables in any part of the file.

**Comment by Chojecki** [comment]
Was thinking about defining vars in `.yaml` file, but all ideas sounds good.

**Comment by Srunels** [comment]
Dart = {{#mason}}{{zackary}}{{/mason}}
Mason = {{#183}}{{zackary}}{{/able}}
Able = {{#183}}{{zackary}}{{/mason}}

**Comment by felangel** [comment]
Curious if you all think these issues would be resolved if there was an alternative syntax for lambdas like:

```
{{#lowerCase}}{{name}}{{/lowerCase}} => {{name.lowerCase()}}
{{#lowerCase}}{{dotCase}}{{name}}{{/dotCase}}{{/lowerCase}} => {{name.dotCase().lowerCase()}}
```

**Comment by Srunels** [comment]
I was curious.. to think mason wasn't the correct name because I do know
the first child to the 2nd child think of it like this mason is zackary
older brother  and since zackary is younger I thought that can't be right
if zackary mother wasn't sub ...

shannawhaley

**Comment by Chojecki** [comment]
Ye, defo more clean and readable
