### ISSUE TITLE
fix: files sort order

### ISSUE THREAD

**Issue by passsy** [felangel/mason#185]
**Description**

Running mason on CI produces a different output than running mason on my local machine. I haven't found out what exactly caused it. It could be a different dart version or a different operating system.

We have one file named `{{name}}` and on CI (linux, dart 2.12) it appear at the top of the `"files": []` list in the generated code.
On macos, dart 2.15 it appears at the very bottom of the list.

**Expected Behavior**
`files` should be explicitly sorted by name, not inherit the file sort of the operating system.

**Screenshots**
![Screen-Shot-2022-01-06-15-20-33 38](https://user-images.githubusercontent.com/1096485/148397114-29001526-a688-4e6a-b249-1f5d2b5f4b20.png)
https://github.com/phntmxyz/sidekick/runs/4727669914?check_suite_focus=true

**Additional Context**
Related PR https://github.com/phntmxyz/sidekick/pull/9

**Comment by felangel** [comment]
Planning to address this issue this afternoon, sorry for the delay!
