### ISSUE TITLE
feat: variable description

### ISSUE THREAD

**Issue by MisterJimson** [felangel/mason#186]
**Description**

When others are using a brick you created, it would be helpful to be able to provide some descriptions for each variable to help them understand what they should put there.

When prompted to enter a value for the variable on the CLI, the description should show.

Here is an example of the output I am thinking about.

```
mason make hello

Provide your full name (e.g Jason Rai), this will be used to ....
name:
```

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by felangel** [comment]
related to #183
