### ISSUE TITLE
fix: mason is init'ing into my Trash directory?

### ISSUE THREAD

**Issue by MisterJimson** [felangel/mason#187]
**Description**
I was playing around with mason and I thought it wasn't working correctly, so I tried to delete the .mason directory to reset everything and start again.

Now whenever I `mason init`, it creates the `.mason` folder in my trash.

```
mason init
✓ Initializing (0.1s)
✓ Getting brick (0.1s)
✓ Generated 3 file(s):
  /Users/jrai/.Trash/mason.yaml (new)
  /Users/jrai/.Trash/bricks/hello/brick.yaml (new)
  /Users/jrai/.Trash/bricks/hello/__brick__/HELLO.md (new)

Run "mason make hello" to use your first brick.
```

**Steps To Reproduce**

I'm not sure of the exact steps to replicate. Something related to deleting .mason and running mason init

**Expected Behavior**
mason init should init into the current directory

**Comment by felangel** [comment]
Hi @MisterJimson 👋 
Thanks for opening an issue!

Are you able to share a screen recording? Are you sure you’re not currently in the Trash when running mason init? Thanks!

**Comment by MisterJimson** [comment]
I think I am getting closer to a reprod case.

Something close to.

```
mason init, get
mason make
cd into new folder from make
trash the new folder
run any(?) mason command (now in the non-existent directory)

mason gets in weird state, stuck in the trash.
```

I'll followup when I can reproduce with exact steps. Seems like something that could happen often if folks are testing bricks with `make` and then trashing them.

**Comment by felangel** [comment]
> I think I am getting closer to a reprod case.
> 
> Something close to.
> 
> ```
> mason init, get
> mason make
> cd into new folder from make
> trash the new folder
> run any(?) mason command (now in the non-existent directory)
> 
> mason gets in weird state, stuck in the trash.
> ```
> 
> I'll followup when I can reproduce with exact steps. Seems like something that could happen often if folks are testing bricks with `make` and then trashing them.

Sounds good, I'll mess around as well and see if I'm able to reproduce.
Can you please share what version of `mason_cli` you're using as well as what OS you're on? Thanks!

**Comment by felangel** [comment]
@MisterJimson hey is there any update on this? I was unable to reproduce the issue locally.

**Comment by MisterJimson** [comment]
I'll reopen with steps If I can consistently reprod. Thanks for taking a look.
