### ISSUE TITLE
error with brick with configurable variables fix: 

### ISSUE THREAD

**Issue by rodrigobastosv** [felangel/mason#195]
I'm getting this error 

`Malformed brick.yaml at /home/rodrigo/Documents/development/projects/vizo/a/bricks/hello/brick.yaml
Unsupported value for "vars". type 'YamlMap' is not a subtype of type 'List<dynamic>?' in type cast` 

while trying to make a brick with configurable variables.

This brick https://github.com/felangel/mason/pull/191/files#diff-84397bfdeb65489b7aa13e101f4a893af93f6acde0181cf6c3bc45476b46a83d is giving this error.

**Comment by felangel** [comment]
Hi @rodrigobastosv 👋
Thanks for opening an issue!

This functionality hasn’t been published yet so if you want to use it you’ll need to install mason from git. Hope that helps 👍
