### ISSUE TITLE
fix: slash (/) in variable is encoded

### ISSUE THREAD

**Issue by passsy** [felangel/mason#211]
**Description**
Adding a slash to a value of a variable writes `&#x2F;` into the file instead of `/`

**Steps To Reproduce**

```dart
vars: {
  'packagePath': 'some/path',
},
```
```bash
// template
{{packagePath}}/tool/run.sh "$@"
```

Result:

```
some&#x2F;path/tool/run.sh "$@"
```

Expected Result:
```
some/path/tool/run.sh "$@"
```

`mason_cli 0.1.0-dev.6`
`mason 0.1.0-dev.4`

**Comment by felangel** [comment]
Hi @passsy 👋
Thanks for opening an issue!

You can use `{{{packagePath}}}` if you want the value to be unescaped. Let me know if that helps 👍
