### ISSUE TITLE
docs: Update the documentation for Windows compatible lambdas

### ISSUE THREAD

**Issue by Fasuh** [felangel/mason#213]
**Description**

I have found an old issue [#59](https://github.com/felangel/mason/issues/59) where lambdas for Windows were fixed, but it is nowhere to be found in the current documentation.

**Requirements**

- Clear description on how to use lambdas on Windows

**Comment by felangel** [comment]
Hi @Fasuh 👋 
Thanks for opening an issue!

#59 was fixed and did not require any changes to be made to lambda usage which is why there is no mention of it in the docs. Is there something that you're still having trouble with?

**Comment by Fasuh** [comment]
Hi @felangel 
my problem is, that i cannot make a file with symbols `/` and `\` in their names.
Which makes me unable to use those mentioned on the `pub.dev` page
![image](https://user-images.githubusercontent.com/39801418/151412100-d85584d9-3a23-44f8-8d90-d5690d6e6446.png)


![image](https://user-images.githubusercontent.com/39801418/151411829-e232a182-5ca3-41d3-a4d4-2da7dbd8ad6a.png)
![image](https://user-images.githubusercontent.com/39801418/151411872-869737a1-de4e-4503-ab4a-144bd1d2f7e7.png)

**Comment by Luckey-Elijah** [comment]
I wonder if enclosing the file name in `"` will work for windows you. I don't use windows anymore so I'd have to ask you to try it it out for me. For example try entering: `"{{snakeCase}}{{name}}{{/snakeCase}}"`in Window explorer or Intellij.

**Comment by Fasuh** [comment]
That doesnt work, `/` is a system character used to split folders, it cannot be used at all
![image](https://user-images.githubusercontent.com/39801418/152514121-bc27c29e-aa04-4359-8831-48b48809fca2.png)

**Comment by jsroest** [comment]
For windows, you need a subfolder to handle the forward-slash `/`.
You might want to have a look at this:
[Allow {{#snakeCase}}{{var_name}}{{/snakeCase}} to be used in files and folders #36](https://github.com/felangel/mason/issues/36)

**Comment by felangel** [comment]
@Fasuh closing for now since @jsroest's comment is accurate. Also check out #183 for future improvements to make this more convenient.
