### ISSUE TITLE
feat: support disabling update check

### ISSUE THREAD

**Issue by ignertic** [felangel/mason#218]
**Description**
Mason Cli keeps prompting to update whenever there is a new release. Automated tasks that invoke the mason_cli in a terminal hang whilst waiting for the developer to either choose yes/no to the update.

**Steps To Reproduce**

1. Wait for a new release of mason_cli
2. Create a bash script that invokes mason to generate a new brick
3. Run Script
4. Notice update prompt awaits input whilst pausing script execution

**Expected Behavior**
Show message of new update but continue execution without blocking 
Or specify an option to skip update checking.

**Comment by felangel** [comment]
This should be resolved in [mason_cli v0.1.0-dev.8](https://pub.dev/packages/mason_cli/versions/0.1.0-dev.8) 🎉
