### ISSUE TITLE
feat: ability to generate several bricks at once with one command

### ISSUE THREAD

**Issue by radomir9720** [felangel/mason#309]
**Description**

Now, to generate several bricks you need to enter several times the command `mason make ...`.

For example:
`mason make brick1 -o ../lib`
`mason make brick2 -o ../lib`
`mason make brick3 -o ../lib`
And so on...

I think it would be great to have the ability to run one command like `mason make "brick1,brick2,brick3"`, and, maybe, something like `mason make -all` which will generate all the bricks.

**Comment by felangel** [comment]
Hi @radomir9720 👋 
Thanks for opening an issue!

Can you please provide a bit more context regarding what these three bricks are? Would it be beneficial to either have a template that contains all the relevant parts of each template (if they are always used together) or per #215 would it help to be able to have templates that can extend other templates?

The main issue I see with make all is how would you specify options for each individual brick? Say for example brick1 requires vars `name`, and `age`. brick2 requires vars `favoriteColor`, and `nickname`, etc...

Let me know what you think, thanks!

**Comment by radomir9720** [comment]
Let's say that i want to instal three completely independent bricks:

1. Theme, and everything that is related to it
2. Firebase helper classes(like `CrashlyticsHelper`, for example)
3. Other packages helper classes. For example, `DeviceInfoHelper`.

And, in my opinion, there may be projects, where i won't use `DeviceInfoHelper`, therefore i don't want to generate code for it.

> The main issue I see with make all is how would you specify options for each individual brick? Say for example brick1 requires vars name, and age. brick2 requires vars favoriteColor, and nickname, etc...

Hmm, i didn't think about it, because in my example there is no need to pass options, and bricks does not have vars at all.

I don't know, maybe this way will be convenient:
`mason make "brick1,brick2,brick3" --brick1 "name=SomeName,age=SomeAge" --brick2 "favoriteColor=SomeColor"`
`mason make -all --brick1 "name=SomeName,age=SomeAge" --brick2 "favoriteColor=SomeColor"`

**Comment by felangel** [comment]
Going to close this for now since in this particular case I’d recommend creating a single brick. You will also likely benefit from #215  once it has been implemented.
