### ISSUE TITLE
feat: mason new command should support generating hooks

### ISSUE THREAD

**Issue by felangel** [felangel/mason#313]
**Description**

As a developer, I want to have hooks generated as part of a brick via the `mason new` command so that I don't need to manually configure hooks from scratch each time.

```sh
# generate both pre_gen and post_gen hooks
mason new my_brick --hooks

# generate only the pre_gen hook
mason new my_brick --hooks pre_gen

# generate only the post_gen hook
mason new my_brick --hooks post_gen
```

**Comment by Luckey-Elijah** [comment]
Could support for a `.gitignore` be generated with the `hooks/` directory?

I find myself excluding the following — (_[for example](https://github.com/Luckey-Elijah/bricks/blob/main/.gitignore#L2-L4)_)
- `.packages`
- `pubspec.lock`
- `.dart_tool`

**Comment by felangel** [comment]
> Could support for a `.gitignore` be generated with the `hooks/` directory?
> 
> I find myself excluding the following — (_[for example](https://github.com/Luckey-Elijah/bricks/blob/main/.gitignore#L2-L4)_)
> 
> * `.packages`
> * `pubspec.lock`
> * `.dart_tool`

yup good call!
