### ISSUE TITLE
Allow {{#snakeCase}}{{var_name}}{{/snakeCase}} to be used in files and folders

### ISSUE THREAD

**Issue by jsroest** [felangel/mason#36]
Hi,
This generator seems to do exactly what I want, besides one thing I can't figure out.

How can I use the #snakeCase, #pascalCase and #camelCase tags in a file or folder name?

The closing tag with the forward slash is not allowed, eg {{/snakeCase}}

**Comment by felangel** [comment]
Hi @jsroest 👋 
Thanks for opening an issue!

You should be able to accomplish this by treating the `/` as a new directory. You can take a look at https://github.com/felangel/mason/blob/master/bricks/todos/__brick__/todos/%7B%7B%23todos%7D%7Dtodo_%7B%7B%7Btodo%7D%7D%7D_todo.md%7B%7B/todos%7D%7D for an example.

Let me know if that helps 👍

**Comment by jsroest** [comment]
Thanks, works like a charm. 🍺
