### ISSUE TITLE
feat(mason_logger): enhance progress API

### ISSUE THREAD

**Issue by felangel** [felangel/mason#361]
**Description**

As a developer, I want to be able to complete, fail, and cancel progress calls via `Logger` so that I can provide a better user experience to developers.

```
final progress = Logger().progress('Doing stuff');

// Complete successfully.
progress.complete('Success');

// Failure -- unable to complete.
progress.fail('Failure');

// Cancel progress.
progress.cancel()
```

**Additional Context**

To maintain backward compatibility we can implement `call()` and proxy to `complete` -- in the future, we can deprecate `call`.

**Comment by bartekpacia** [comment]
It'd also be great if I could do:

```dart
progress.update('the action I intended to do failed, but I know a workaround and I'm applying it now...')`
```

:)
