### ISSUE TITLE
feat: Allow global use of `mason make` with discoverable mason.yaml

### ISSUE THREAD

**Issue by craiglabenz** [felangel/mason#366]
**Description**

Currently, a developer has to run all of their `mason` commands from within the single folder containing their global `mason.yaml` file. This prevents creating a new directory, navigating into it, and running `mason make <whatever>` to generate code directly at that location.

Allowing developers to set a `MASON_HOME` environment variable (or similar) would enable `mason_cli` to orient itself from any location on their machine.

**Comment by felangel** [comment]
Hi @craiglabenz 👋
Thanks for opening an issue!

This is already possible 🎉
Just use `mason add -g` to install the brick globally and you can use `mason make` In any directory on your machine.

Hope that helps!

**Comment by felangel** [comment]
@craiglabenz did my previous reply help? Let me know if there’s anything I can do 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional thoughts and I’m happy to continue the conversation 👍
