### ISSUE TITLE
docs(question): how to disable variable replacement

### ISSUE THREAD

**Issue by mugbug** [felangel/mason#367]
**Description**

Is there a way to avoid a `{{ secrets.GITHUB_TOKEN }}` string to be understood as a variable and replaced? I wanted to create a template that has a GitHub Actions workflow file but can't figure out how to avoid the `${{ secrets.GITHUB_TOKEN }}` string to be changed to just `$`

**Comment by felangel** [comment]
Hi @mugbug 👋
Thanks for opening an issue!

You can use the `mustacheCase` lambda for that:

```
{{#mustacheCase}}secrets.GITHUB_TOKEN{{/mustacheCase}}
```

Let me know if that helps 👍

**Comment by mugbug** [comment]
Hey @felangel! Thanks for the quick reply!

Hm, the `mustacheCase` just seems to have the same result as using a the `{{` tags. Still getting `{{ secrets.GITHUB_TOKEN }}` completely removed. Any thoughts?

Some info that might help:
- `mason --version == 0.1.0-dev.25`
- my bricks are local (not using github url or mason hub)

**Comment by mugbug** [comment]
Hmm, it seems to be missing a release with this one for `mason_cli` https://github.com/felangel/mason/commits/master/packages/mason_cli, I'll try to just install it from master to try out!

**Comment by mugbug** [comment]
Using `master` now it worked like a charm! Thanks a lot @felangel!

**Comment by felangel** [comment]
> Using `master` now it worked like a charm! Thanks a lot @felangel!

Just published a new release of mason_cli so you should be able to `dart pub global activate mason_cli`

**Comment by mugbug** [comment]
Awesome, thanks!
