### ISSUE TITLE
feat(vscode): support creating files from bricks through vscode extension

### ISSUE THREAD

**Issue by mugbug** [felangel/mason#375]
**Description**

Today we have a `mason` vscode extension that supports managing bricks (like adding, removing, etc). 

I think this extension could be even more powerful if it supports consuming the bricks to generate files directly through the vscode interface.

**Requirements**

- [ ] Add support for mason's `make` command through vscode interface.

**Additional Context**

The idea is to achieve something like what there is on Bloc's extension:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/19307199/171020514-0c74fb99-1114-4cda-9578-7e1f9ef7f5cd.png">

Presenting all locally and globally installed bricks as alternative when creating files/folders.

Is it possible to do? If so, let me know how can I help with this!

**Comment by felangel** [comment]
Hi @mugbug 👋
Thanks for opening an issue!

I’m actively working on this and am aiming to have an initial version available sometime this week 🙂

**Comment by mugbug** [comment]
Wow, awesome! Thanks again @felangel! And let me know if I can help in any way with this =]
