### ISSUE TITLE
feat: add brick search/lookup to `mason_cli`

### ISSUE THREAD

**Issue by Luckey-Elijah** [felangel/mason#379]
**Description**

Add a mason CLI command to search registered bricks on `brickhub.dev`.
```sh
mason search <search-string>
```
That will return identical results from the `https://brickhub.dev/search?q=` query.

**Requirements**

- [x] Add a `MasonApi().search(String query)` method
- [x] Add a Search Result model to `mason_api`
- [x] Add `search` command
- [x] `search` command will return an abbreviated list of `brickhub.dev` search results in executing terminal

**Example**
```
$ mason search bloc
Searching "bloc" on brickhub.dev...
bloc_page
  A brick to create a page with view and bloc
  v0.2.0(this month)jm@remeur.fr

replay_cubit
  Generate a new ReplayCubit in Dart. Built for the bloc state management library.
  v0.1.0(last month)felangelov@gmail.com

replay_bloc
  Generate a new ReplayBloc in Dart. Built for the bloc state management library.
  v0.1.0(last month)felangelov@gmail.com

hydrated_cubit
  Generate a new HydratedCubit in Dart. Built for the bloc state management library.
  v0.1.0(last month)felangelov@gmail.com

hydrated_bloc
  Generate a new HydratedBloc in Dart. Built for the bloc state management library.
  v0.1.0(last month)felangelov@gmail.com
  ```

**Comment by felangel** [comment]
Hi @Luckey-Elijah 👋 
Thanks for opening an issue!

Out of curiosity is there an analogous command for `pub`, `npm` or any other package manager that you're aware of? Thanks!

**Comment by Luckey-Elijah** [comment]
Perhaps for "one-line" results, just 10 results — keep it identical to the `brickhub.dev` search results for now.

And maybe provide a flag to query more.

```sh
mason search bloc --limit=20
```

**Comment by felangel** [comment]
> Perhaps for "one-line" results, just 10 results — keep it identical to the `brickhub.dev` search results for now.
> 
> And maybe provide a flag to query more.
> 
> ```shell
> mason search bloc --limit=20
> ```

Seems reasonable to me.

Just out of curiosity what made you request this feature? Is it more convenient to use the CLI for search?

**Comment by Luckey-Elijah** [comment]
> Just out of curiosity what made you request this feature?

I'm just familiar with searching packages in the terminal via `brew search` and seemed natural to have a search feature for mason 😄. 
> Is it more convenient to use the CLI for search?
I don't search brickhub.dev frequently but there's been about 3 or 4 occasions I would have preferred to stayed in the terminal (less key strokes)

**Comment by felangel** [comment]
> Perhaps for "one-line" results, just 10 results — keep it identical to the `brickhub.dev` search results for now.

Thanks for providing some additional context! I'm fine with you working on this but I think I'll need to expose the search API via `package:mason_api` since the core api is not publicly documented at the moment and we shouldn't scrape brickhub.dev for search results.
