### ISSUE TITLE
feat: allow importing local files in hooks

### ISSUE THREAD

**Issue by alestiago** [felangel/mason#382]
**Description**

Allow importing local hook files in `pre_gen.dart` and `post_gen.dart`.

**Requirements**

- [ ] Allow importing local files in hooks.

**Additional Context**

Useful for complex hooks and for sharing logic between them.

**Comment by vanlooverenkoen** [comment]
Any idea when this will be implemented? This is a feature that would optimize our workflow a lot!

**Comment by felangel** [comment]
> Any idea when this will be implemented? This is a feature that would optimize our workflow a lot!

@vanlooverenkoen planning to implement this some time this coming week -- sorry for the delay!

**Comment by wolfenrain** [comment]
Would love to have this functionality as well! Would clear up my code base quite a bit.
