### ISSUE TITLE
feat: `mason bundle` should be able to watch a brick

### ISSUE THREAD

**Issue by wolfenrain** [felangel/mason#384]
**Description**

As a developer I want to be able to watch a brick directory and have it rebundle whenever something in the brick changes.

This would allow for quicker testing of code that depend on mason bundles.

**Requirements**

- [ ] extend current bundle command so it can watch a brick and rebundle it to the given output
- [ ] Ensure this feature works on all platforms

**Additional Context**

A simple `--watch` flag might already do it for the bundle command.

**Comment by felangel** [comment]
It probably also makes sense to have this functionality on `mason make`

**Comment by alestiago** [comment]
For any readers, I'll be working on this functionality. I will first work on `mason make --watch` 🙌

**Comment by alestiago** [comment]
@felangel we might want to keep this open since #1131 tackles `make` as suggested by your [comment](https://github.com/felangel/mason/issues/384#issuecomment-1267052342) but not `bundle` as requested by @wolfenrain .
