### ISSUE TITLE
fix(mason_logger): Allow for printing when `Progress` is running

### ISSUE THREAD

**Issue by bartekpacia** [felangel/mason#385]
**Description**

When something is printed to the terminal while `Progress` is running, the progress line is duplicated. It doesn't look good.

I unfortunately don't have time to create reproducible example, it's fine if you close this because it's not reproducible without sample code.

**Comment by felangel** [comment]
Hi @bartekpacia 👋 
Thanks for opening an issue!

I think this is working as expected because ideally things should not be printed while something is in progress. Can you provide some more context regarding what you're trying to achieve? Thanks!

**Comment by felangel** [comment]
Closing for now since there aren’t any actionable next steps. Feel free to comment with additional info and I’m happy to continue the conversation 👍

**Comment by bartekpacia** [comment]
Hi @felangel! I'm reviving this issue :)

Let's say that I have the following method:

```dart
Future<void> _installServer({
    required String device,
    required bool debug,
  }) async {
    await _disposeScope.run((scope) async {
      final progress = log.progress('Installing server');
      try {
        await _forceInstallApk(
          path: _artifactsRepository.serverArtifactPath,
          device: device,
          packageName: _serverPackage,
        );
      } catch (err) {
        progress.fail('Failed to install server');
        rethrow;
      }

      progress.complete('Installed server');
    });
  }
```

Locally, it works fine, but when run on GitHub Actions (so a non-interactive shell), the output is pretty horrible:

![Screenshot 2022-09-20 at 11 25 04 PM](https://user-images.githubusercontent.com/40357511/191367563-5526a16b-2e0c-4164-a0fd-ce014bc97784.png)

**Comment by bartekpacia** [comment]
Ping @felangel :)

**Comment by felangel** [comment]
> Hi @felangel! I'm reviving this issue :)
> 
> Let's say that I have the following method:
> 
> ```dart
> Future<void> _installServer({
>   required String device,
>   required bool debug,
> }) async {
>   final progress = log.progress('Installing server');
>   try {
>     await _forceInstallApk(
>       path: _artifactsRepository.serverArtifactPath,
>       device: device,
>       packageName: _serverPackage,
>     );
>   } catch (err) {
>     progress.fail('Failed to install server');
>     rethrow;
>   }
>   progress.complete('Installed server');
> }
> ```
> 
> Locally, it works fine, but when run on GitHub Actions (so a non-interactive shell), the output is pretty horrible:
> 
> ![Screenshot 2022-09-20 at 11 25 04 PM](https://user-images.githubusercontent.com/40357511/191367563-5526a16b-2e0c-4164-a0fd-ce014bc97784.png)
> 
> Any idea how we could make this better? Maybe disabling the spinner so it wouldn't actually spin when the shell is non-interactive would help?

Yeah we can update the behavior to be static in non-interactive shells 👍

Although, this issue was tracking being able to interleave logs during a progress call so I don’t think it’s the same issue. Do you mind opening a new issue to track this?

**Comment by bartekpacia** [comment]
> Yeah we can update the behavior to be static in non-interactive shells

I'd love this!

> Although, this issue was tracking being able to interleave logs during a progress call so I don’t think it’s the same issue. Do you mind opening a new issue to track this?

Sure! See #528. Sorry for mixing these 2 issues.
