### ISSUE TITLE
feat: add additional nav options to `mason_logger`'s `chooseOne`

### ISSUE THREAD

**Issue by Luckey-Elijah** [felangel/mason#398]
**Description**

When using `chooseOne` I would like to be able to use 
- <kbd>J</kbd> to move down
- <kbd>K</kbd> to move up
- <kbd>Space</kbd> to make a selection

**Requirements**

- [ ] <kbd>J</kbd> to move down
- [ ] <kbd>K</kbd> to move up
- [ ] <kbd>Space</kbd> to make a choice selection

**Additional Context**

These is vim-like key binds.

_P.S. I'm building myself some internal tooling hence all the activity on this repo 🙂_

**Comment by felangel** [comment]
Hi @Luckey-Elijah 👋 
Thanks for opening an issue!

I think this makes sense. The only question I have is about `Space` to make a selection. The reason I ask is because I'm working on `chooseAny` (to allow zero or more selections) and in that implementation `Enter` is used to submit the responses and `Space` is used to toggle the selected state of an individual response. Let me know what you think and thanks again!

**Comment by felangel** [comment]
> I don't mind _not_ using Space for `chooseOne` — so if it's a huge overhead, we don't have to implement it.
> 
> But could `chooseAny` and `chooseOne` use Space differently? I think the proposed Space functionality would be natural/intuitive for each of the implementations.

Just want to make sure I understand:

1. Keep `chooseOne` as is but add `Space` as a way to submit (in addition to `Enter`)
2. `chooseAny` supports `Space` to select/deselect and `Enter` to submit

Is that accurate?

**Comment by Luckey-Elijah** [comment]
Yes! That's what I had in mind.

**Comment by felangel** [comment]
I can just make the change along with the chooseAny should be able to get that done later today 👍

**Comment by felangel** [comment]
@Luckey-Elijah I'm assuming you'd also want J/K support to move up/down for the `chooseAny` API right?

**Comment by Luckey-Elijah** [comment]
> @Luckey-Elijah I'm assuming you'd also want J/K support to move up/down for the `chooseAny` API right?

Yes  🙂

**Comment by felangel** [comment]
Should be available in mason_logger v0.1.0-dev.12 🎉
