### ISSUE TITLE
feat: let us change the location of `$HOME/.mason-cache` 

### ISSUE THREAD

**Issue by bartekpacia** [felangel/mason#402]
As the title says. I'd like to be able to write in my shell `rc` file:

```
export MASON_CACHE_PATH=`$HOME/.config/mason` # let's not clutter my `$HOME` :)
```

Maybe this is already possible, but after 1 minute of searching, I couldn't find such option.

**Comment by felangel** [comment]
Hi @bartekpacia 👋
Thanks for opening an issue!

You can set the `MASON_CACHE` environment variable 👍
