### ISSUE TITLE
feat(mason_logger): progress.update

### ISSUE THREAD

**Issue by felangel** [felangel/mason#403]
It'd also be great if I could do:

```dart
progress.update('the action I intended to do failed, but I know a workaround and am applying it now...')`
```

:)

_Originally posted by @bartekpacia in https://github.com/felangel/mason/issues/361#issuecomment-1150931058_

**Comment by Luckey-Elijah** [comment]
👋🏻 I really like this feature request. As an interface I think something like this would be nice:

```dart
Future<void> main() async {
  final calculating = Logger().progress('Calculating'); // State A
  await someFuture();
  calculating.update('Halfway!'); // State B
  await someFuture();
  calculating.complete('Done!'); // State C
}

Future<void> someFuture() => Future<void>.delayed(const Duration(seconds: 2));

```

And output State A:
```
⠸ Calculating...
```
State B:
```
⚑ Halfway! (2.0s)
⠦ Calculating...
```
State C:
```
⚑ Halfway! (2.0s)
✓ Done! (4.0s)
```

This means that the `update` will only write to `stdout` and _not_ change the original `progress` message (`'Calculating'` in this example).

**Comment by bartekpacia** [comment]
Personally, I'd prefer `update()` not to do persist text.  I can't explain this clearly, so I'll modify @Luckey-Elijah example from above :)

So:

And output State A:

```
⠸ Calculating...
```

State B:

```
⠦ Halfway! (2.0s)
```

State C:

```
✓ Done! (4.0s)
```

**Comment by Luckey-Elijah** [comment]
Yes that makes sense. I actually think I like that more 🙂

**Comment by Luckey-Elijah** [comment]
@felangel if you think this feature may be added, feel free to assign me and I'd like to start on it 🙂
