### ISSUE TITLE
fix: Cannot publish brick with enum type as a variable - Malformed bundle: BrickVariableProperties

### ISSUE THREAD

**Issue by LukeMoody01** [felangel/mason#410]
**Description**

When using an enum as a variable type in your brick, when you go to publish the brick you will get the following error:

"Unrecognized keys: [values]; supported keys: [type, description, default, prompt]"

**Steps To Reproduce**

1. Create a brick with an enum variable type
2. Publish the brick
3. See error

**Expected Behavior**

Developer should be able to publish a brick when using an enum as a variable.

**Screenshots**

![image](https://user-images.githubusercontent.com/73887660/173031910-67e5144d-652a-407c-9536-57c9862c324e.png)

**Additional Context**

Had a look at the code and it seems this error is coming from the API. So unfortunately I cannot help much 😁

**Comment by felangel** [comment]
Hi @LukeMoody01 👋
Thanks for opening an issue!

This is because you need to update your version of mason_cli (since enum and array support was only recently added). Can you try updating mason_cli and let me know if you’re still having trouble publishing? Thanks!

**Comment by LukeMoody01** [comment]
Yup I have the latest version "0.1.0-dev.29"

**Comment by felangel** [comment]
Ah yeah I need to upgrade the backend to use the latest version of mason. Give me 15 mins and should be good to go. Sorry for the inconvenience!

**Comment by LukeMoody01** [comment]
All good! I thought that was the case so I mentioned it in the ticket 😁

Thanks!

**Comment by felangel** [comment]
@LukeMoody01 should be updated now. Can you try publishing again?

**Comment by LukeMoody01** [comment]
Yup working all good now. Thanks for the quick fix!
