### ISSUE TITLE
fix: `chooseOne` `j` and `k` key navigate in the wrong direction

### ISSUE THREAD

**Issue by Luckey-Elijah** [felangel/mason#413]
**Description**

When using `chooseOne` <kbd>J</kbd> and <kbd>K</kbd> to navigate, each move in the wrong direction.

Issue #398 for reference :)

**Steps To Reproduce**

```dart
Future<void> main() async {
  final logger = Logger();

  final favoriteColor = logger.chooseOne(
    'Pick a color.',
    choices: ['red', 'green', 'blue'],
    defaultValue: 'blue',
  );

  logger.info('Got it, $favoriteColor it is!');
}
```

```sh
dart run main.dart
```
Navigate with  <kbd>J</kbd> and <kbd>K</kbd>.

**Expected Behavior**

<kbd>J</kbd> to move down
<kbd>K</kbd> to move up

**Version**
demo at commit 0b555b9

**Screenshots**

![Screen Recording 2022-06-13 at 11 21 18 AM mov](https://user-images.githubusercontent.com/38171761/173388115-0b6fd22b-61b7-4a4b-beac-3407ef0f6871.gif)

**Comment by Luckey-Elijah** [comment]
Feel free to assign to me, and I can implement the fix 🙂

**Comment by felangel** [comment]
> Feel free to assign to me, and I can implement the fix 🙂

Ah oops good catch! Assigned to you, thanks! 🙏
