### ISSUE TITLE
feat: support log levels

### ISSUE THREAD

**Issue by felangel** [felangel/mason#420]
**Description**

As a developer, I want to be able to configure a log level for my logger instance so that I can control the level of granularity in the logs. Need to create a proposal first before working on an implementation.

**Comment by wolfenrain** [comment]
After discussing this with @felangel, I have come up with the follow proposal.

Introduce a `LogLevel` enum, that can be passed to the `Logger` constructor: 

```dart
enum LogLevel {
  detail,
  info,
  error,
  warn,
  alert,
  success,
  all,
}
```

By default the `Logger` will use `all` to ensure it is backwards compatible.

Internally we can have an extension on the `LogLevel` to return an integer for each level and use that for each of the log methods to determine if it should log or not:

```dart
class Logger {
  Logger({
    this.level = LogLevel.all,
  });

  final LogLevel level;

  @override
  void info(String? message) {
    if (level.level < LogLevel.info.level) {
       return;
    }
    ...
  }

  ...
}

extension on LogLevel {
  int get level {
    switch (this) {
      case LogLevel.detail:
        return 100;
      case LogLevel.success:
      case LogLevel.info:
        return 200;
      case LogLevel.warn:
        return 400;
      case LogLevel.error:
        return 500;
      case LogLevel.alert:
        return 600;
     case LogLevel.all:
     	return 1000;
    }
  }
}
```

I chose not to use enhanced enums so we can keep the package useable for dart 2.16 and therefore not introduce a breaking change.

**Comment by felangel** [comment]
@wolfenrain thanks so much for the proposal! The only comment I had was about inverting the LogLevel values to be ascending in order of priority like:

```dart
extension on LogLevel {
  int get level {
    switch (this) {
     case LogLevel.all:
     	return 0;
      case LogLevel.detail:
        return 100;
      case LogLevel.success:
      case LogLevel.info:
        return 200;
      case LogLevel.warn:
        return 400;
      case LogLevel.error:
        return 500;
      case LogLevel.alert:
        return 600;
    }
  }
}
```

Otherwise the proposal sounds great to me, lmk what you think 👍
