### ISSUE TITLE
fix: Escape greater than and less than sign

### ISSUE THREAD

**Issue by masreplay** [felangel/mason#426]
**Description**

I want to pass variable data type as generic Pagination<Order> but after it gets given the generated code will be like Pagination&lt;Order&gt;

**Steps To Reproduce**

1. pass < or > to prompt
2. go to generated code
3. &lt;&gt;

**Expected Behavior**

the greater than or equal less than must appear in the code as sign

**Screenshots**

<img width="430" alt="image" src="https://user-images.githubusercontent.com/55885230/175473296-86ddf8c4-5780-4855-b456-063cab3f6c0e.png">
<img width="168" alt="image" src="https://user-images.githubusercontent.com/55885230/175473348-16222e86-92e1-4c29-b3b8-875def982cd8.png">

**Additional Context**

**Comment by felangel** [comment]
Hi @masreplay 👋
You can use triple mustache brackets to unescape variables:

`{{{var}}}`

Hope that helps!

**Comment by masreplay** [comment]
It worked, thanks @felangel 👋
