### ISSUE TITLE
fix: allow passing a dynamic array to prompt

### ISSUE THREAD

**Issue by masreplay** [felangel/mason#429]
**Description**

Can't pass a dynamic array to prompt 

**Steps To Reproduce**

1. mason make cubit --repositories (["user", "auth", "realEstate"])
2. I also try to pass params as ([user, auth, realEstate])

**Expected Behavior**

allow the list like - values

**Screenshots**

<img width="714" alt="image" src="https://user-images.githubusercontent.com/55885230/175807812-2ab397d6-99f5-46b7-8a49-465bee38b5f7.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/55885230/175807941-4a45dcb6-59a6-45de-aed7-fdd639465157.png">

**Additional Context**

**Comment by masreplay** [comment]
Hi @felangel 🖤
is it possible to make the syntax easier to write?
like this
mason make cubit --repositories [user, auth, realEstate]

**Comment by felangel** [comment]
@masreplay you should also be able to do:

```
mason make cubit --repositories '["user", "auth", "realEstate"]'
```

Let me know if that helps 👍

**Comment by masreplay** [comment]
Yeah of course it's a little easier
