### ISSUE TITLE
feat: if/else with clause condition

### ISSUE THREAD

**Issue by vasilich6107** [felangel/mason#430]
**Description**

Before creating this issue I investigated the repository to find if `mason` already supports what I need.
I've found `{{#isDev}}` and `{{^isDev}}` for booleans.

What I need is an ability to write `var == 'String' ? a : b`. or `if(var == 'String') { a }`

For example I have an input if type that I need to generate template for.
I need to call different methods from https://pub.dev/packages/shared_preferences depending on the value type like
- `getString` for `String`
- `getBool` for `bool`

and so on.

**Comment by LukeMoody01** [comment]
Hey @vasilich6107 👋

For now, you could use the pre_gen.dart hook to create some custom variables that depend on the input!

```
void run(HookContext context) {
  final yourCustomValue = context.vars['var'] == 'String' ? a : b
  context.vars = {
    ...context.vars,
    'yourCustomValue ': yourCustomValue ,
  };
}
```

Then you can write what you had above `{{#yourCustomValue}}` or `{{^yourCustomValue}}`

Hope this helps!

**Comment by felangel** [comment]
Closing for now since there are no actionable next steps. Feel free to comment with any follow-up questions and I'm happy to continue the conversation 👍
