### ISSUE TITLE
feat: do not generate empty line in place of if clause

### ISSUE THREAD

**Issue by vasilich6107** [felangel/mason#431]
**Description**

When adding multiple if clauses like

```
  @override
  {{#isBool}}Future<{{type}}?> read() => _localStorage.readSecureBool(_keyToken);{{/isBool}}
  {{#isString}}Future<{{type}}?> read() => _localStorage.readSecure(_keyToken);{{/isString}}
  {{#isInt}}Future<{{type}}?> read() => _localStorage.readSecureInt(_keyToken);{{/isInt}}
```

template generated

```
  @override
  
  
  Future<int?> read() => _localStorage.readSecureInt(_keyToken);
```

There are some empty lines. It would be great to have 
```
  @override
  Future<int?> read() => _localStorage.readSecureInt(_keyToken);
```

**Comment by felangel** [comment]
Hi @vasilich6107 👋
Thanks for opening an issue!

You can achieve the desired outcome by moving all the conditionals on the same line:

```
  @override
  {{#isBool}}Future<{{type}}?> read() => _localStorage.readSecureBool(_keyToken);{{/isBool}}{{#isString}}Future<{{type}}?> read() => _localStorage.readSecure(_keyToken);{{/isString}}{{#isInt}}Future<{{type}}?> read() => _localStorage.readSecureInt(_keyToken);{{/isInt}}
```

Hope that helps!

**Comment by felangel** [comment]
Unfortunately that’s how mustache works. I’m working on expanding support to other templating engines in the future. Sorry for the inconvenience!

**Comment by felangel** [comment]
> No problem)
> We can leave this issue just as a reminder or close it - whatever you prefer

I prefer to close it as there aren’t any actionable steps for mustache in particular.
