### ISSUE TITLE
fix: mason publish does not accept expected input

### ISSUE THREAD

**Issue by cgutierr-zgz** [felangel/mason#434]
**Description**

The command `mason publish` throws an error when trying to publish a new brick with the name `42_project`, I would assume it fails for other similar namings.

**Steps To Reproduce**

1. Create a brick called `42_project`
2. Run `mason publish` inside the brick
3. See the error
 _**Output:**_

```bash
mason publish
```
>✓ Bundled 42_project (0.0s)
>
>Publishing is forever; bricks cannot be unpublished.
>See policy details at https://brickhub.dev/policy
>
>Do you want to publish 42_project 0.1.0? (y/N) Yes
>✗ Publishing 42_project 0.1.0 (0.9s)
>Malformed bundle.
>42_project is not a valid name.
>The name should be all lowercase, with underscores to separate words (e.g. my_awesome_brick).
>Use only basic Latin letters and Arabic digits: [a-z0-9_].

**Expected Behavior**

Reading the output `Use only basic Latin letters and Arabic digits: [a-z0-9_]` I would assume `42_project` is a valid name for a brick, and I should be able to publish.

**Screenshots**

<img width="665" alt="Screenshot 2022-06-28 at 14 47 08" src="https://user-images.githubusercontent.com/18635739/176182072-ad25d24d-4b19-4686-8fcd-2d17b1928d10.png">

**Additional Context**

The brick works as expected locally, it's only the publishing part.

**Comment by felangel** [comment]
Hi @cgutierr-zgz 👋
Thanks for opening an issue!

A brick name cannot start with a number. I can update the error to make it more explicit 👍
