### ISSUE TITLE
chore: Should bricks check for missing dependencies and add them if neccessary?

### ISSUE THREAD

**Issue by LosDanieloss** [felangel/mason#446]
I'm new to the mason and bricks. Came here after watching YouTube video posted by Flutter team. Tried few of bricks and it seems that they all have one in common. They don't add dependencies to pubspec.yaml if they relay on any e.g., brick that generates model class using freezed don't check and include build_runner, freezed or json_serializable dependencies. 
This get me wondering... Is it good practice or should I aim to also include those when creating my own bricks?

**Comment by LosDanieloss** [comment]
Thanks for quick response. Yes it helps. But raises another question. Should that `post_gen.dart` script also be responsible for running `build_runner`? For the sake of completeness and be error-free I'd imagine yes.

**Comment by felangel** [comment]
> Thanks for quick response. Yes it helps. But raises another question. Should that `post_gen.dart` script also be responsible for running `build_runner`? For the sake of completeness and be error-free I'd imagine yes.

It's up to the brick maintainer to decide but in my opinion yes, it would be good to run build_runner for the users (if necessary). You may even be able to generate the relevant code as part of the brick (rather than relying on an additional code generation step).

**Comment by LosDanieloss** [comment]
Thank you for clarifications
