### ISSUE TITLE
Lambdas on MacOS partially work

### ISSUE THREAD

**Issue by andrzejchm** [felangel/mason#447]
# Description

using lambdas in filenames on macOS is not working correctly, using alternative exit lambda sign (`\` instead of `/`) makes intellij not showing the template file at all, see screenshots below.

here is a bug report for IntelliJ: https://youtrack.jetbrains.com/issue/IDEABKL-6091/IDEA-handles-files-with-non-separator-slashes-incorrectly

# Expected Behavior
In general I believe using `\` and `/` in filenames is not really a good idea as those are either path separators in some systems or escape chhars. If possible, I'd suggest using other syntax, i.e:

```
{{#snakeCase}}{{name}}{{^#snakeCase}}
```

# Screenshots

## Case with `/` in name 
![CleanShot 2022-07-10 at 16 09 06@2x](https://user-images.githubusercontent.com/1711474/178148572-db0e5989-dcc4-415f-a6f7-ced1d95ac181.png)

## Case with `\` in name 

![CleanShot 2022-07-10 at 16 13 42@2x](https://user-images.githubusercontent.com/1711474/178148807-4ec2c31e-c823-4c09-b42f-b4592137119f.png)

**Comment by felangel** [comment]
Hi @andrzejchm 👋
This is a duplicate of https://github.com/felangel/mason/issues/36 and you can alternatively use the lambda shorthand syntax: https://github.com/felangel/mason/tree/master/packages/mason_cli#built-in-lambdas.

Hope that helps 👍

**Comment by andrzejchm** [comment]
Thank you for your fast reply @felangel 

I've checked, the shorthands dont work either:
![CleanShot 2022-07-10 at 20 09 47@2x](https://user-images.githubusercontent.com/1711474/178156948-edb63d41-8e4f-47a2-bdd1-bba7afe09097.png)

What I did instead, I've created `pre_gen.dart`  hook that adds new variables with the snake case names and use those instead. this works like a charm :) Although I think the shorthand syntax could be fixed as its right now not usable in filenames.

Anyways, thank you VERY much for this project, it is going me lots of time and $$$ :))

**Comment by felangel** [comment]
> Thank you for your fast reply @felangel
> 
> I've checked, the shorthands dont work either: ![CleanShot 2022-07-10 at 20 09 47@2x](https://user-images.githubusercontent.com/1711474/178156948-edb63d41-8e4f-47a2-bdd1-bba7afe09097.png)
> 
> What I did instead, I've created `pre_gen.dart` hook that adds new variables with the snake case names and use those instead. this works like a charm :) Although I think the shorthand syntax could be fixed as its right now not usable in filenames.
> 
> Anyways, thank you VERY much for this project, it is going me lots of time and $$$ :))

Thanks! Can you please provide a minimal reproduction sample? Also, are you using the latest version of mason?

**Comment by andrzejchm** [comment]
you're right! I had older dart version thus was using `0.1.0-dev.10`. I've now updated dart and mason to `0.1.0-dev.30` and it works like a charm! Sorry for bothering :)
