### ISSUE TITLE
feat: Add path dependencies to Hooks

### ISSUE THREAD

**Issue by vanlooverenkoen** [felangel/mason#449]
**Description**

It is not possible to add a path dependency, I think the hooks pubspec will be resolved from the wrong location

`path: ../../` does not work when running from ../../ where the brick is located

**Requirements**

- [ ] Support for path dependencies

**Comment by felangel** [comment]
Hi @vanlooverenkoen 👋 
Thanks for opening an issue!

This is a duplicate of #382.
