### ISSUE TITLE
Run MasonGenerator on "make" Command

### ISSUE THREAD

**Issue by woroud-alnaeb** [felangel/mason#461]
I have a brick that I use to multiple purposes and to pass a list of attributes that will be used to generate code from another internal brick.
I do not want to access internal brick directly but I want to **automatically** run MasonGenerator to generate multiple copies of the internal one from the external brick when I **make** the external one, is there a way to achieve this?

**Comment by felangel** [comment]
Hi @woroud-alnaeb 👋 
Thanks for opening an issue!

You can use a `pre_gen.dart` hook in your `external` brick to programmatically generate code from internal bricks. See https://github.com/LukeMoody01/mason_bricks/blob/6aae6ad057bb071e6c66f5a9bd2194f339af1791/bricks/service_package/hooks/pre_gen.dart#L44 for an example, hope that helps 👍
