### ISSUE TITLE
feat: Add `link` ansi wrapper

### ISSUE THREAD

**Issue by Luckey-Elijah** [felangel/mason#462]
**Description**

Add an ANSI wrapper that enables hyperlinks/links in the terminal. More info at this [Gist](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) on how to achieve the desired effect.

I've done this in one of my projects, but I think it might server others as well.

**Requirements**

- [ ] API to "wrap" a string with a link for stdout.

**Additional Context**

An example API:

```dart
Future<void> main() async {
  Logger(level: Level.verbose).info(
    linkWrap(
      'You can find issues here',
      'https://github.com/felangel/mason/issues/',
    ),
  );
}
```
```dart
String linkWrap(String message, String link) {
  final uri = '\x1B]8;;$link\x1B\\';
  final text = '$message\x1B]8;;\x1B\\';
  return '$uri$text';
}
```
<img width="657" alt="hyperlink" src="https://user-images.githubusercontent.com/38171761/179578392-363ea2f2-6484-43f9-bd53-a18ad2373708.png">

**Comment by Luckey-Elijah** [comment]
@felangel would you accept a PR for this feature? If so, feel free to assign to me

**Comment by felangel** [comment]
> @felangel would you accept a PR for this feature? If so, feel free to assign to me

Yes, I'd love to add this 👍

**Comment by Luckey-Elijah** [comment]
I don't think using `AnsiCode` will work with it's `wrap` method since it doesn't take a second parameter for something like a "link".

I like to propose a top-level function `link`, a method on the `Logger`, or a new class for this (similar to `AnsiCode`).

The top-level function `link` or a `link` method on `Logger` would make the most sense. A new class just for wrapping a message with link is a bit overkill.

```dart
// "wraps" given string with a link, then returns the value
String linkWrap(String message, Uri uri) { ... }

void main() {
  final logger = Logger(level: Level.verbose);
  final issuesLink = linkWrap(
    'see issues here',
    Uri.parse('https://github.com/felangel/mason/issues/'),
  );
  logger
    ..info(issuesLink)
    ..warn(issuesLink)
    ..err(issuesLink);
}
```

```dart
class Logger {
  void link(
    String message,
    Uri uri, [
    void Function(String)? write,  // uses [info] by default
  ]) { ... }
}

void main() {
  final logger = Logger(level: Level.verbose);
  final issuesUri = Uri.parse('https://github.com/felangel/mason/issues/');
  logger
    ..info(issuesLink)
    ..warn(issuesLink)
    ..err(issuesLink);
}
```

Woth implementations would be identical in output:

<img width="632" alt="Screen Shot 2022-09-14 at 2 02 12 PM" src="https://user-images.githubusercontent.com/38171761/190228919-3a94f264-b781-4e75-a521-1fc337a743be.png">

Personally I like `Logger.link` interface the most
