### ISSUE TITLE
fix: Could not find brick at https://github.com/felangel/mason

### ISSUE THREAD

**Issue by lavahasif** [felangel/mason#479]
**Description**

**Steps To Reproduce**

1. `mason_cli: ^0.1.0-dev.32`
2.  execute ```mason add -g bio --git-url https://github.com/felangel/mason ```   

**Expected Behavior**

✓ Made brick bio (0.1s)
✓ Generated 1 file:

**Error showing**
Could not find brick at https://github.com/felangel/mason

**Screenshots**
![image](https://user-images.githubusercontent.com/22430922/180656094-7837f903-d43e-4968-8c50-d9e06ce24222.png)

**Additional Context**

i executed my brick hosted on github .it did'nt working .same result coudn't find brick.
but add brick from local it working 
![image](https://user-images.githubusercontent.com/22430922/180656316-f52fed17-1b30-454c-99fd-866c550c940f.png)

**Comment by felangel** [comment]
Hi @lavahasif 

You need to specify the git path as well since the brick isn’t at the root of the repo:

`mason add -g bio --git-url https://github.com/felangel/mason --git-path bricks/bio`

**Comment by lavahasif** [comment]
@felangel  thank you it worked 
look this package work without mention --git-path .how it is ? could you give info?
![image](https://user-images.githubusercontent.com/22430922/180657717-55f0cdc7-6aea-4cd7-b8a4-936711da5b05.png)

**Comment by felangel** [comment]
> @felangel thank you it worked look this package work without mention --git-path .how it is ? could you give info? ![image](https://user-images.githubusercontent.com/22430922/180657717-55f0cdc7-6aea-4cd7-b8a4-936711da5b05.png)
> 
> **reporduce** `mason add -g app_ui --git-url https://github.com/LukeMoody01/mason_bricks`
> 
> That reason i confused. it show error

It seems that command also errored. You need to provide the path to the brick if it’s not at the root of the repository. I can try to improve the error messaging in the above case 👍

**Comment by felangel** [comment]
Closing for now since it is working as expected

**Comment by lavahasif** [comment]
` mason add -g ck --git-url https://github.com/lavahasif/ct   `   

**How  the project structure?**

![image](https://user-images.githubusercontent.com/22430922/180659888-82503bd5-f3a3-40c6-a6a2-80e3e4173756.png)

**Output**

![image](https://user-images.githubusercontent.com/22430922/180659877-d5277c7f-6837-4cd4-9b61-8102ca101d68.png)

thanks felangel it works
