### ISSUE TITLE
fix: Could not find brick at E:/CodeSAmple/flu/dbhelper/dbhelper.i coud'nt execute make command and list command on mason

### ISSUE THREAD

**Issue by lavahasif** [felangel/mason#480]
**Description**

I coud'nt execute make command and list command on mason cli. it showing coud not find brick at .It was working .suddenly happening like this. i restart my system and deactivate mason_cli

**Steps To Reproduce**
**first case** 
1. `mason list -g`
###  second case
1.mason add -g feature_brick
2.mason make feature_brick

**Expected Behavior**
while execute first case
![image](https://user-images.githubusercontent.com/22430922/180797488-0fde80f2-f979-4054-a862-4e15dd516ac8.png)

**Screenshots**
show error while listing global brick (first case)
![image](https://user-images.githubusercontent.com/22430922/180797775-3cd9973e-384e-4ba6-9468-946372f1ca30.png)
while making the brick on any directory from brickhub.dev or self (second case)
![image](https://user-images.githubusercontent.com/22430922/180798079-096a8c73-e7bd-43b2-b1bf-4c0722a0116b.png)

***Additional Context*****

It was working perfectly .Now showing like this.

**Comment by felangel** [comment]
Hi @lavahasif 👋
Thanks for opening an issue!

Did you install the bricks locally (without the -g flag)? If so can you try to install them again (mason get)?

If you installed them globally then you can try to re-add them via mason add -g.

If you’re still having trouble you can try wiping the mason cache via (mason cache clear).

Let me know if that helps!

**Comment by lavahasif** [comment]
> Hi @lavahasif 👋 Thanks for opening an issue!
> 
> Did you install the bricks locally (without the -g flag)? If so can you try to install them again (mason get)?
> 
> If you installed them globally then you can try to re-add them via mason add -g.
> 
> If you’re still having trouble you can try wiping the mason cache via (mason cache clear).
> 
> Let me know if that helps!

 i execute `mason cache clear` still the issue 

i remove the folder

`E:/CodeSAmple/flu/dbhelper/dbhelper`

**Comment by lavahasif** [comment]
could you .. how i reinstall mason . just delete the cache folder .but same error showing.i tried pub activate and reactivate same effect

**Comment by lavahasif** [comment]
[Check here you can find solution ](https://github.com/felangel/mason/issues/486)
