### ISSUE TITLE
feat(vars): Conditional variable input 

### ISSUE THREAD

**Issue by yardexx** [felangel/mason#482]
Hello

I was trying mason when I got to this problem

**Description**

I want to omit paramaters completly (= not bother other devs by hiting enter for nothing) because I don't need them -  they are in part of file which won't be generated because of previous boolean variable.

Model situation:
Let dev to choose whether to generate code for Android or iOS or both. For Android, package name is needed. For iOS, bundle ID is needed. But if dev chooses Android only, mason shouldn't ask about bundle ID (iOS related information).

Not sure if this is somehow achievable (I got through all materials and issues), so posting this as feat propose.

Apologies if this is already a thing.

**Comment by felangel** [comment]
Hi @yardexx 👋
Thanks for opening an issue!

This is already possible via a pre_gen hook. You can inspect the current variables via context.vars and then conditionally prompt using the built in logger (context.logger).

Let me know if that helps 👍

**Comment by yardexx** [comment]
👍  That's what I was looking for. Thanks. 

btw. Love, VGV packages, keep up the good work <3
