### ISSUE TITLE
fix: coud'nt find brick .cant execute make command on  brick global or local .

### ISSUE THREAD

**Issue by lavahasif** [felangel/mason#484]
**Description**

I coud'nt execute make command and list command on mason cli. it showing coud not find brick at .It was working .suddenly happening like this. i restart my system and deactivate mason_cli

**Steps To Reproduce**
**first case** 
1. `mason list -g`
###  second case
1.mason add -g feature_brick
2.mason make feature_brick

**Expected Behavior**
while execute first case
![image](https://user-images.githubusercontent.com/22430922/180797488-0fde80f2-f979-4054-a862-4e15dd516ac8.png)

**Screenshots**
show error while listing global brick (first case)
![image](https://user-images.githubusercontent.com/22430922/180797775-3cd9973e-384e-4ba6-9468-946372f1ca30.png)
while making the brick on any directory from brickhub.dev or self (second case)
![image](https://user-images.githubusercontent.com/22430922/180798079-096a8c73-e7bd-43b2-b1bf-4c0722a0116b.png)

***Additional Context*****

It was working perfectly .Now showing like this.

**Comment by felangel** [comment]
Hi 👋 
This looks like a duplicate of #480.

**Comment by lavahasif** [comment]
where i need to copy that folder E:\  to c:\
this my mason.bat folder from c drive
![image](https://user-images.githubusercontent.com/22430922/182031835-d1f1f77b-8a98-444a-b94f-1e1416723d6b.png)

can you suggest reinstallation approach

**Comment by lavahasif** [comment]
[Check here you can find solution ](https://github.com/felangel/mason/issues/486)
