### ISSUE TITLE
fix: Add brick from git by path doesn't work

### ISSUE THREAD

**Issue by MbIXjkee** [felangel/mason#485]
Adding brick from git doesn't work.

mason add elementary --git-url https://github.com/Elementary-team/flutter-elementary --git-path tree/main/packages/elementary_tools/elementary_bricks/elementary/

Maybe the reason is monorepo.

**Comment by felangel** [comment]
Hi @MbIXjkee 👋
The git path should be relative to the root of the repo so in this case I believe it should be:

`mason add elementary --git-url https://github.com/Elementary-team/flutter-elementary --git-path packages/elementary_tools/elementary_bricks/elementary`

Hope that helps 👍

**Comment by MbIXjkee** [comment]
Hi @felangel. Thank you, this helped. I think will be good to show it in the documentation.

**Comment by MbIXjkee** [comment]
Or maybe add examples even.

**Comment by felangel** [comment]
I tried to show this in the mason.yaml that is generated when you run mason init. I’m working on a dedicated docs site so this should be covered when that goes live 👍
