### ISSUE TITLE
fix: unintentionally delete or rename the global brick path affect the global /local mason command. like list ,make commands.

### ISSUE THREAD

**Issue by lavahasif** [felangel/mason#486]
**Description**

 unintentionally delete or rename the global brick path affect the global /local mason command. like list ,make commands.
[#480](https://github.com/felangel/mason/issues/480) [484](https://github.com/felangel/mason/issues/484)

**Steps To Reproduce**

delete or rename the brick you registerd as global .
execute `mason ls -g`
**Expected Behavior**

coud'nt find brick if it available or it from brickhub.dev

**Screenshots**

![image](https://user-images.githubusercontent.com/22430922/182082825-27fec48a-2ab5-4501-9653-7afaacc57dbf.png)

**Additional Context**
### Solution:
mostly in windows mason cache folder. **C:\Users\{username}\AppData\Local\Mason\Cache\global** .

![image](https://user-images.githubusercontent.com/22430922/182083124-63659272-bca2-417d-8e11-31824f7b293a.png)

you can look at here the path .check the correct name of the path or exist
![image](https://user-images.githubusercontent.com/22430922/182083332-bac5c2ce-dc43-47fd-88e4-3d3458ea9c42.png)
remove each brick that not exist.

![image](https://user-images.githubusercontent.com/22430922/182083622-31cf8ac9-31a0-4643-9027-8b20e61a59ac.png)

now list the brick .it works .

![image](https://user-images.githubusercontent.com/22430922/182083885-c31c8424-9885-4f56-99f2-f37b25cd2981.png)

i think problem here .if any brick not found it affect whole brick system.plesase consider solution for this

![image](https://user-images.githubusercontent.com/22430922/182084102-9e97d54e-7d45-48a1-9b58-9d7e89da750d.png)

**Comment by felangel** [comment]
In my opinion, this is working as expected because you shouldn't be modifying the files is the mason cache directory by hand. Going to close this for now but if you are aware of any steps that lead to the corruption of the mason cache please let me know and I'm more than happy to take a closer look and work on a fix 👍
