### ISSUE TITLE
Support for Regex

### ISSUE THREAD

**Issue by felangel** [felangel/mason#5]

**Comment by orestesgaolin** [comment]
I imagine a way to provide a regex e.g. to add line in build.gradle inside the dependencies node

**Comment by felangel** [comment]
Closing this for now because rather than trying to figure out a way to bake this in, I feel it's better to write a Dart CLI which replaces the desired lines with template strings and uses `mason` as a dependency to generate the code from the template using the `MasonGenerator.fromGitPath` API.
