### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by dhrubrawat66** [felangel/mason#500]
I use this command "mason make very_good_dart_package --project_name "todos_data_source" --description "A generic interface for managing todos." -o packages"
the i got this issue "

command failed with this message==>Could not find an option named "project_name".

**"C:\Users\dhrub\Desktop\Screenshot 2022-08-22 145545.png"**

**Comment by dhrubrawat66** [comment]
this was tested in window operating system.

**Comment by felangel** [comment]
Hi @dhrubrawat66 👋
Thanks for opening an issue!

I already responded to your issue once [on the Dart Frog repo](https://github.com/VeryGoodOpenSource/dart_frog/issues/287) and you never replied. Can you please follow up this time?

Can you please run the following commands and share the output?

`mason --version`

`mason ls`
`mason ls -g`

**Comment by dhrubrawat66** [comment]
![Screenshot 2022-08-22 215121](https://user-images.githubusercontent.com/85351405/185967422-b3edf0f7-7fc9-493a-a84b-48fcd15f087c.png)

**Comment by dhrubrawat66** [comment]
after these command i got these output

**Comment by felangel** [comment]
Hi @dhrubrawat66 👋 
That means you haven't installed the `very_good_dart_package` template. You need to install it first via:

```
mason add -g very_good_dart_package
```

Then you should be able to run `mason make ...` and the package should be generated. Let me know if that helps 👍

**Comment by dhrubrawat66** [comment]
thank you. it woks.
