### ISSUE TITLE
fix: enum values selection using arrow_keys

### ISSUE THREAD

**Issue by Hisham-Tariq** [felangel/mason#501]
**Version**
mason 0.1.0-dev.34
**Description**

Enum Values can't be selected except first one as the arrow keys does not take to any other value.

**Steps To Reproduce**

1. Create a array field
2. values:
      - development
      - integration
      - staging
      - production
3.  get and make the brick

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/63235813/186740536-7f25b216-a2ad-4a7a-a728-b981a43872f5.png)

**Comment by Hisham-Tariq** [comment]
Yes i tried but arrow keys not navigating between options

**Comment by felangel** [comment]
> Yes i tried but arrow keys not navigating between options

Can you provide a link to a minimal reproduction sample? Are you able to push your brick to GitHub?

**Comment by Hisham-Tariq** [comment]
Hi I just used the flavors brick with this command which gave the same error

mason add flavors --git-url https://github.com/felangel/mason --git-path bricks/flavors

**Comment by Rushi-creates** [comment]
@Hisham-Tariq try using 'j' and 'k' keys on the keyboard to move up and down respectively, and use spacebar to select/deselect and press enter to finish

**Comment by felangel** [comment]
Closing for now since there are no actionable next steps but feel free to comment with additional information if the issue persists.
