### ISSUE TITLE
feat: allow search on bricks installed globally on users system and generate the brick selected from the search results

### ISSUE THREAD

**Issue by rutvik110** [felangel/mason#505]
**Description**

The current search for bricks through mason, allows one to search bricks present on brickhub.dev . I would love to see search on bricks installed globally on users system. And allow the user to select a brick from the search results and generate it upon selection.

Preview : 

https://user-images.githubusercontent.com/65209850/187836705-0aec0e49-07f6-48ad-93fc-e4a7707be4ed.mp4

**Requirements**

- [x] Allow searching bricks installed globally on users system
- [x] Ability to install a brick by selecting one from the search results

**Additional Context**

This will be helpful when the user has lots of bricks installed globally and want to quickly search for a particular brick and generate that brick.

**Comment by felangel** [comment]
Hi @rutvik110 👋
Thanks for opening a PR. I believe this functionality is supported via `mason ls -g`. Let me know if that helps!

**Comment by rutvik110** [comment]
So, the default global list of bricks from mason presents you with all of the globally installed bricks. But, this addition allows you to search globally installed bricks like you would do with `mason search $brickname`. And on top of that, you can select the brick right away from the search results and follow up with its generation.

I believe this can speed up things if you're trying to find a brick when you've lots of bricks installed and some of which may have lengthy names you may not remember. 
Wdyt?

**Comment by Luckey-Elijah** [comment]
Additionally for the search, `mason search -i <q>` and `mason search -r <q>` could  _only_ search bricks that are _installed_ or _registered_ at `registry.brickhub.dev` (respectively).

**Comment by felangel** [comment]
Closing this since we have added CLI completion via #660. Now you can type `mason make` and press tab to see all available bricks and tab through the list to select the desired brick.
