### ISSUE TITLE
fix: Generated Files limited to max 248 files

### ISSUE THREAD

**Issue by andikapratama** [felangel/mason#510]
**Description**

Currently mason can only generate a maximum of 248 files, the rest are skipped. 

**Steps To Reproduce**

1. Use my sample brick with a 1000 file here https://github.com/andikapratama/mason_file_limit
2. run `mason make file_limit`
3. See that only 248 files are generated

**Expected Behavior**

All 1000 files should be generated. But instead, only 248 file is generated

**Screenshots**

<img width="499" alt="Screen Shot 2022-09-06 at 18 19 11" src="https://user-images.githubusercontent.com/915845/188623089-c1cafc31-e728-4c12-b373-9d9ad9921e31.png">

**Additional Context**

-

**Comment by LukeMoody01** [comment]
Hey @andikapratama 👋

I thought this issue was interesting so I pulled your brick and gave it a go, and I was able to generate all 1000 files:
![image](https://user-images.githubusercontent.com/73887660/189011946-10805d2b-664c-4f5e-9d52-acadf5537d24.png)

Are you on the latest version of mason? 
And also, what system are you on (Mac, Windows, Linux)?

I tested this on Windows 11 (I can also test on Mac if that is what you are on)

**Comment by andikapratama** [comment]
Oh it worked on Windows 11? I tested this on Mac, on currently latest mason
(0.1.0-dev34)

**Comment by felangel** [comment]
@andikapratama you may need to up the limit of the number of processes via ulimit.

`ulimit -u unlimited`

https://access.redhat.com/solutions/61334

**Comment by andikapratama** [comment]
Thanks @felangel , setting the ulimit worked.

But unfortunately mac's ulimit will reset back to 256 everytime I close the terminal, so i had to do it everytime, which is annoying.

In my opinion, this should still be considered a bug, because shouldn't mason try to close the files after writing them during generation, instead of opening and writing all the files all at once? This way by default it will work as expected on all platforms.

**Comment by felangel** [comment]
> Thanks @felangel , setting the ulimit worked.
> 
> But unfortunately mac's ulimit will reset back to 256 everytime I close the terminal, so i had to do it everytime, which is annoying.
> 
> In my opinion, this should still be considered a bug, because shouldn't mason try to close each files on the queue after writing them during generation, instead of opening and writing all the files all at once? This way by default it will work as expected on all platforms.

Agreed, I'll dig into this shortly.

**Comment by felangel** [comment]
This should be resolved in `mason v0.1.0-dev.32` 🎉
