### ISSUE TITLE
fix: Relative paths in mason.yaml should resolve relative to mason.yaml (not the current working directory)

### ISSUE THREAD

**Issue by oravecz** [felangel/mason#515]
**Description**

In mason.yaml, the relative path to a brick should resolve to the location of 
mason.yaml and not the current working directory when running mason commands.
For example, `mason upgrade` resolves paths to bricks (e.g. ./path/to/brick) 
relative to the directory I am in when I run the command, causing my defined 
bricks to not be discovered.

**Steps To Reproduce**

1. Add a brick specifying a relative path from mason.yaml
2. Navigate to another folder in your project
3. Run `mason upgrade`
4. Receive "Could not find brick at <relative path resolved to current working directory>

**Expected Behavior**

My expectation is that wherever I am in my project, when I run `mason upgrade` it will resolve paths similar to how `mason make` does -- relative to the `mason.yaml` configuration file

**Comment by felangel** [comment]
Hi @oravecz 👋 
Thanks for opening an issue!

Good catch, I'll try to get a fix in later today. Sorry for the inconvenience!

**Comment by felangel** [comment]
@oravecz this should be resolved in [mason_cli v0.1.0-dev.35](https://pub.dev/packages/mason_cli/versions/0.1.0-dev.35) 🎉
