### ISSUE TITLE
docs: How to specify file name with pascalCase

### ISSUE THREAD

**Issue by Chojecki** [felangel/mason#53]
**Description**

When I want to add new file with `{{#snakeCase}}{{name}}{{/snakeCase}}.dart` template, the `/` char will break name in `VS Code` and create a `Folder` called `{{#snakeCase}}{{name}}{{` with file `snakeCase}}.dart`

Any Idea how to create it?

**Requirements**

- [x ] use VS Code

**Comment by felangel** [comment]
Hi @Chojecki 👋
Thanks for opening an issue!

I believe this is a duplicate of #36. It’s working as expected, when you generate using `mason make` it will generate the file 👍

**Comment by Chojecki** [comment]
Nice, thanks!
