### ISSUE TITLE
fix: Can't import template from git on Windows

### ISSUE THREAD

**Issue by Fasuh** [felangel/mason#56]
**Description**
After filling up `mason.yaml` im getting an error

`FileSystemException: Exists failed, path = 'C:\Users\bbkk9\AppData\Local\Mason\Cache\git\git@github.com:Fasuh/mason_template.git' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
`
the same conficuration works on MacOS

**Steps To Reproduce**

rather self explanatory

**Expected Behavior**
I would expect Mason to import my templates from git.

**Comment by felangel** [comment]
Sorry for the inconvenience! I should have a fix for this by tomorrow 👍

**Comment by Fasuh** [comment]
Thanks for the fix

**Comment by felangel** [comment]
This should be resolved now in [v0.0.1-dev.32](https://pub.dev/packages/mason/versions/0.0.1-dev.32) 🎉
