### ISSUE TITLE
feat: Don't include blank lines when conditional content is excluded

### ISSUE THREAD

**Issue by matthew-carroll** [felangel/mason#585]
**Description**

I'm using mustache guards to conditionally display information.

```markdown
Hello

{#some_guard}
This is information that won't show if `some_guard` is `false`.
{/some_guard}

World!
```

When `some_guard` is `false` I would expect:

```markdown
Hello


World!
```

But I think what I'm seeing in my generates files is:

```markdown
Hello




World!
```

I could collapse the guards down to one line, but I think that makes it more difficult to read, and I think it would still result in one extra line, instead of two.

**Comment by felangel** [comment]
Hey 👋 
I believe this is working as intended according to the mustache spec. mason uses package:mustache_template internally for the templating so it probably makes sense to move the issue there if you feel this behavior should change.

**Comment by matthew-carroll** [comment]
Ok. Unfortunate that they did that, but oh well.
