### ISSUE TITLE
feat: Question, is it possible to add a directory/file based on a variable value (boolean)

### ISSUE THREAD

**Issue by ArielFerreiro** [felangel/mason#586]
I wonder if there is a way to add an entire directory or a specific file based on the value of a boolean variable.

Example: var add_feature_x = true, generates the content of a directory or specific file, otherwise skip it.

Something similar to what can be done in a content of a file with {{#}} and {{^}} but with the directory structure itself.

Thank you!

**Comment by felangel** [comment]
Hi @ArielFerreiro 👋
Thanks for opening an issue!

Yes you can 🙂
Check out https://github.com/felangel/mason/tree/master/bricks/plugin/__brick__ for an example and let me know if you have questions.
