### ISSUE TITLE
feat: Is there support for complex user questionnaires?

### ISSUE THREAD

**Issue by matthew-carroll** [felangel/mason#587]
**Description**

I have a use-case which involves asking the user a number of questions that depend upon earlier questions. The user might go through various routes of questioning. At the end, all of the user's answers assemble into a configuration, which guides the generation of code.

I'm wondering if there's anything in `mason` that's intended to facilitate these use-cases, or if `mason` just provides the user I/O and leaves these details to clients?

**Comment by felangel** [comment]
Hi @matthew-carroll 👋
This is a perfect use-case for using a pre_gen hook and the logger api. You can collect the necessary information and build up the configuration dynamically. Hope that helps!

**Comment by matthew-carroll** [comment]
That's just basic I/O, though, right? There aren't any APIs for constructing that question graph?

**Comment by felangel** [comment]
> That's just basic I/O, though, right? There aren't any APIs for constructing that question graph?

Yup at the moment but happy to discuss any potential enhancements that can be made.

**Comment by matthew-carroll** [comment]
I think I'll take a stab at creating a package for that structure. I'll need to ask the same questions outside of `mason`, too, so probably better as a separate package.
