### ISSUE TITLE
feat: prompt to select a brick

### ISSUE THREAD

**Issue by iChicago** [felangel/mason#596]
**Description**

**Problem:**
I usually don't memorize what bricks are available globally. So I try to list them using `mason list -g` then, I copy the brick's name and then run `mason make selectedTemplate`. 

**Suggested Solution:**
I would love to make it easier by doing `mason make` which prompts a list of the installed bricks. Then I select the required one. 

**Suggested Solution2:**
I would love to make it easier by doing `mason make` 
Then I hit TAP twice. 
Then I can use the completion mechanism to select the desired brick.

This would save some time and avoid typing errors when writing brick's name.

Thanks

**Comment by felangel** [comment]
Completion has been added to mason_cli via #660 🎉
