### ISSUE TITLE
fix(mason_logger): Windows terminals not showing animation progress

### ISSUE THREAD

**Issue by LukeMoody01** [felangel/mason#619]
**Description**

When running the creation of bricks that use the Logger.progress method, the animation is not shown on windows terminals.

I did some testing and this is caused by the stdioType check, in PR #582 
It seems the stdioType for windows is 'static'(See below screenshot). Not too sure how this will pan out in checking for this?

**Steps To Reproduce**

Windows Device:
1. Open a cmd/powershell/vscode terminal
2. Run a brick with an animation (A simple demo animation pre-hook will do)
3. Verify result (Animation only shows first frame)

**Expected Behavior**

When on windows, the user should be able to see the animation in powershell/cmd/vscode terminal

**Screenshots**

![image](https://user-images.githubusercontent.com/73887660/201499431-6678ba63-5444-4dc8-9b4f-d1fca2771129.png)

**Additional Context**

N/A

**Comment by felangel** [comment]
Hey @LukeMoody01 👋 
Thanks for catching this! It should be resolved in `mason_logger v0.2.3` and you should be able to re-activate `mason_cli` to upgrade your logger version:

`dart pub global activate mason_cli`

**Comment by LukeMoody01** [comment]
Legend! Thanks, @felangel! 👏
