### ISSUE TITLE
docs: Generation of version.dart in mason_cli

### ISSUE THREAD

**Issue by jksevend** [felangel/mason#632]
**Description**

Hey :) 
This is just a simple question: **How did you generate the version.dart in the mason_cli?**

I assume the ``build_runner`` package has something to do with this but my research on this topic was not really successful.
Right now I just hardcode the version in a file but generating seems like a much better approach.

**Comment by felangel** [comment]
Hi @jksevend 👋 
It's generated using [`package:build_version`](https://pub.dev/packages/build_version).
