### ISSUE TITLE
fix: VS Code complains 'No mason installation has been found.' but mason-cli actually works

### ISSUE THREAD

**Issue by theideasaler** [felangel/mason#649]
**Description**

I have created several bricks and works fine with CLI in my project, but the extension keeps complaining 'No mason installation has been found.' when I tried to create brick with VS Code UI. 

https://marketplace.visualstudio.com/items?itemName=FelixAngelov.mason

Any clue to fix this issue?

**Comment by felangel** [comment]
Hi @theideasaler 👋
Thanks for opening an issue!

This error means the mason command cannot be found via your VSCode terminal. Can you verify that opening a new terminal in VSCode and typing mason returns the usage information for mason?

**Comment by theideasaler** [comment]
Hi @felangel , yes I tried 'mason --version' which gives me the correct version numbers.

**Comment by theideasaler** [comment]
> > Hi @felangel , yes I tried 'mason --version' which gives me the correct version numbers.
> 
> Are you trying the command in the VSCode integrated terminal or in a separate shell?
I tried it in the integrated terminal

**Comment by felangel** [comment]
> > > Hi @felangel , yes I tried 'mason --version' which gives me the correct version numbers.
> > 
> > 
> > Are you trying the command in the VSCode integrated terminal or in a separate shell?
> 
> I tried it in the integrated terminal

Are you able to provide a screen recording which illustrates the issue?

**Comment by theideasaler** [comment]
@felangel Thanks for your reply. This issue is not reproducible after I reinstalled my VS Code. Seems to be an random issue

**Comment by felangel** [comment]
Closing for now then feel free to reopen if you are able to reproduce.
