### ISSUE TITLE
fix: issue with mustache syntax

### ISSUE THREAD

**Issue by marcotrumpet** [felangel/mason#662]
**Description**

Based on an array, try looping in it to generate one file per item in the array and access the item value in the corresponding file.
NOTE -> this issue happens only when the code is poorly written but I needed a couple of tries to figure it out (if the dart code is correct there are no issues).

**Steps To Reproduce**

1. Go to this gist https://gist.github.com/marcotrumpet/1e4b4c421529adbd8cc1681424d4f65c
2. Copy the pre_gen code into hook
3. Create a fine into __brick__ with following path `{{#arrayValues}}{{{valueName}}}_name_checker.dart{{/arrayValues}}`
4. Copy in it the [name_checker.dart](https://gist.github.com/marcotrumpet/1e4b4c421529adbd8cc1681424d4f65c#file-name_checker-dart) file content
5. run `mason make`

**Expected Behavior**

No specific expected behavior. Don't know if it's possible to evaluate {{arrayValues.valueName}} besides the wrong dart code or if an error can be thrown in the cli.

**Screenshots**
As you can see the generated file doesn't evaluate {{arrayValues.valueName}}
<img width="616" alt="Screenshot 2022-12-11 alle 17 32 47" src="https://user-images.githubusercontent.com/35219231/206916202-a30291ac-a7fd-41d4-8b10-be1ed01fa7b1.png">

**Comment by felangel** [comment]
Hi @marcotrumpet 👋 
Thanks for opening an issue!

I believe the issue is due to the fact that this expression is not interpreted as valid due to the imbalanced brackets. I think you should be able to rewrite it as:

```dart
void main() {
  final String testString = '${{#mustacheCase}}{{arrayValues.valueName}}.capitalize(){{/mustacheCase}}
}
```

Let me know if that helps 👍

**Comment by marcotrumpet** [comment]
Yeah for sure first of all the code example is wrong. This helps for sure. The thing that puzzles me is that if you have more than one call to `{{arrayValues.valueName}}` if one is broken then all of them are. I think it definitely has something to do with the render method from mustache_template but not sure.
By the way, thanks a lot!
