### ISSUE TITLE
feat: Add List of config 

### ISSUE THREAD

**Issue by mstfkhazaal** [felangel/mason#669]
Add a list of configuration instead of one
### Before:
**config.json**
```
{
    "name": "Felix",
}
```

### After:
**config.json**
```
[
    {
        "name": "felangel",
    },
    {
        "name": "Felix",
    }
]
```

**Comment by felangel** [comment]
Hi @mstfkhazaal 👋
Thanks for opening an issue!

Can you please provide a bit more context regarding why you want these changes? What should be the output of running mason make with a configuration file containing multiple configs?

**Comment by mstfkhazaal** [comment]
I create a brike to create bloc with repo & presentation with multiple params
Instead of writing it more than once in the cmd with params
i run the one time and then mason run multiple time with params

Simply as if you were writing the code more than once

**Comment by mstfkhazaal** [comment]
If there is a way to add bricks to config that would be better
Example:
have 5 briks (brick1,brick2,brick3,brick4,brick5)
[
    {
        "name": "felangel",
        "brick": "brick1",
        "onConflict": "append"
    },
    {
        "name": "Felix",
        "brick": "brick2",
        "onConflict": "overide"
    }......
]

**Comment by felangel** [comment]
Hi @mstfkhazaal there are a couple of ways to do this:

1. Create a new brick which uses pre_gen hooks to generate code for multiple other bricks. See the [flutter_bloc_feature](https://github.com/felangel/bloc/blob/master/bricks/flutter_bloc_feature/hooks/pre_gen.dart) for an example.
2. Write a dart script which uses `package:mason` to do this.
3. Write a bash script which runs the mason_cli multiple times with the correct args/config.

Closing for now but feel free to comment if none of those suggestions work for you and I'm happy to continue the conversation 👍
