### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by hussenIbrahim** [felangel/mason#674]
**Description**

cannot add  brick globally  (Brick "firstbricks" does not exist.)

**Steps To Reproduce**

1. mason init
2. mkdir bricks
3. mason new firstbricks
4. mason add firstbricks-g

**Expected Behavior**
brick must be added globally
![Screenshot 2022-12-20 164429](https://user-images.githubusercontent.com/62293873/208681367-c4da04aa-6018-4aea-a917-c992ececc38f.png)

**Additional Context**

Win 11 ,  mason_cli version 0.1.0-dev.41

**Comment by felangel** [comment]
Hi @hussenIbrahim 👋
Thanks for opening an issue!

If you want to install a brick globally from a local path you need to use the `--path` option like:

`mason add -g firstbrick --path ./firstbrick`.

You can refer to the docs at https://docs.brickhub.dev/mason-add.

**Comment by hussenIbrahim** [comment]
i forgot to add brick to mason.yaml
thank
