### ISSUE TITLE
feat: add GitHub Gist support

### ISSUE THREAD

**Issue by tyler-jewell** [felangel/mason#682]
**Description**

Would it be possible to store brick templates in a GitHub Gist and integrate with mason?

This would avoid the need for a repository being created for each brick you develop. 

The user would create a mustache template as a Gist and then convert that to a brick via Brick.gist. 

The only concern is the variable configuration since this will be a single file. The user would need to provide these in the code itself before generation

**Requirements**

- [ ] Sanity check
- [ ] Configuring mustache variables (since we won't have a YAML with the template)
- [ ] Add Brick.gist feature

**Additional Context**

- https://gist.github.com/

**Comment by felangel** [comment]
Hi @tyler-jewell 👋
Thanks for opening an issue!

You don’t need one repository per brick. You can also have a single repository with all of your bricks. Check out https://github.com/felangel/bloc/tree/master/bricks for an example.

Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now since there aren't any actionable steps. Feel free to comment with any follow up questions/thoughts and I'm happy to continue the conversation 👍
