### ISSUE TITLE
fix: mason_logger progress weird behaviour in android studio terminal

### ISSUE THREAD

**Issue by shan-shaji** [felangel/mason#694]
**Description**

`progresss` function inside `MasonLogger` is showing a weird behaviour when running in android studio terminal.

**Steps To Reproduce**

This behaviour happens when running the function in android studio terminal. 

**Expected Behavior**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/42430941/211140872-4bb952f6-fb07-400a-bdc2-b637a6bc35ff.gif)

**Screenshots**

<img width="1401" alt="Screenshot 2023-01-07 at 1 34 40 PM" src="https://user-images.githubusercontent.com/42430941/211140642-83f1315f-41a1-47b1-8aff-3ca824424f31.png">

**Comment by felangel** [comment]
Hi @shan-shaji 👋
Thanks for opening an issue!

Are you using the latest version of mason_logger? If you are, then can you share the version of android studio? If you aren’t using the latest version of mason_logger can you please try upgrading and confirm whether you’re still experiencing this issue? Thanks!

**Comment by shan-shaji** [comment]
Thanks @felangel i have upgraded the `mason_logger` version and the issue is fixed. I am closing the issue.

**Comment by felangel** [comment]
> Thanks @felangel i have upgraded the `mason_logger` version and the issue is fixed. I am closing the issue.

Awesome, glad to hear it 🎉

**Comment by shan-shaji** [comment]
@felangel I think the very_good_cli template logger version is ` mason_logger: ^0.2.0`.
