### ISSUE TITLE
fix: Hooks Pre-gen error

### ISSUE THREAD

**Issue by Makarov96** [felangel/mason#707]
**Description**

When run comman: mason make <Brik_Name> -o packages/ and this are created with hooks, return the next error:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/51811904/213901574-d1ba5280-1eb2-45d8-b2e4-ad2d1a7f2993.png">

**Steps To Reproduce**

1. Create a brick with hooks
2. run this brick using mason make <Brick_Name>

**Expected Behavior**

 run pre-gen.dart file  without error

**Screenshots**
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/51811904/213901623-cd9f052f-8f3c-469a-bae8-d73f7a81f493.png">

**Comment by Makarov96** [comment]
The solution: 
Re-Install mason

**Comment by felangel** [comment]
> The solution:
> Re-Install mason

Glad you managed to get it working!
