### ISSUE TITLE
`Logger.warn` always shows brackets, even if tag is empty

### ISSUE THREAD

**Issue by bartekpacia** [felangel/mason#715]
[Logger.warn](https://pub.dev/documentation/mason_logger/latest/mason_logger/Logger/warn.html) accepts `String tag` as an argument. Unfortunately, if the tag is empty, the log looks like:

```
[] This is my log
```

I'd like to be able to call `warn()` without a tag, so that the `[` and `]` would not be visible.

**Comment by felangel** [comment]
Thanks for the issue and good catch! Will fix this shortly!

**Comment by bartekpacia** [comment]
💙 💙 💙 💙 💙
