### ISSUE TITLE
fix: Every command runs twice

### ISSUE THREAD

**Issue by aadarshadhakalg** [felangel/mason#73]
**Description**
On executing any mason command the command is executed twice simultaneously. 

**Steps To Reproduce**

1. On windows install mason globally 
2. Open cmd/powershell
3. run mason --version
4. See the version is printed twice

**Expected Behavior**
The version should only be printed once.

**Screenshots**
![image](https://user-images.githubusercontent.com/19362725/121235414-971f2000-c8b4-11eb-92af-5b91db648502.png)

**Additional Context**

**Comment by felangel** [comment]
Hi @aadarshadhakalg 👋 
Thanks for opening an issue!

I'm guessing you have multiple installations of `mason`. This can happen if you run different commands to install `mason`:

`pub global activate mason`
`dart pub global activate mason`
`flutter pub global activate mason`

I recommend trying to deactivate `mason`

`pub global deactivate mason`
`dart pub global deactivate mason`
`flutter pub global deactivate mason`

And then reinstall it via `dart pub global activate mason`. Let me know if that helps 👍

**Comment by aadarshadhakalg** [comment]
Hey felangel,

Even though I was preety sure that there weren't multiple installations. I tried to deactivate and again activate it. But, unfortunately it didn't work. 

![image](https://user-images.githubusercontent.com/19362725/121281092-146b8480-c8f7-11eb-9db8-bd5ee7d8c24e.png)

**Comment by felangel** [comment]
@aadarshadhakalg I believe this is related to https://github.com/dart-lang/pub/issues/2934 and is not specific to `mason`. If you deactivate `mason` and you try to run `mason --version` does it still work?

```sh
$ dart pub global deactivate mason
$ mason --version
```

**Comment by aadarshadhakalg** [comment]
Yeah, it worked! Thank you @felangel  .

**Comment by amebrahimi** [comment]
It helped me too. Thank you. 🙏
