### ISSUE TITLE
Is it possible to generate a brick inside another brick?

### ISSUE THREAD

**Issue by SSebigo** [felangel/mason#739]
**Description**

**Short**:
I would like to know if it is possible to call a brick inside another brick and if it's possible, how can I do it?

**Long**:
Say I have this brick ```application```:
```
application
├── __brick__
│   └── lib
│       └── application
│           └── {{name.snakeCase()}}
│               ├── {{name.snakeCase()}}_bloc.dart
│               ├── {{name.snakeCase()}}_event.dart
│               └── {{name.snakeCase()}}_state.dart
└── brick.yaml
```
I have three other bricks like this one that can be called in standalone (e.g. ```mason make application```).

Now, let's say I have this other brick ```feature```:
```
feature
├── __brick__
│   └── lib
│       ├── {{application}}
│       ├── {{domain}}
│       ├── {{infrastructure}}
│       └── {{presentation}}
└── brick.yaml
```

What I would like to do, is to generate these other bricks inside this one to generate this entire tree.
I mean, I could just rewrite the same things from these bricks inside ```feature```, but it's pretty wasteful to do that.

**Requirements**

- [ ] Generate bricks inside another brick

**Comment by felangel** [comment]
Hi @SSebigo 👋
Thanks for opening an issue!

Currently you can achieve this by using hooks but we’re also working on making this simpler in the future (#215). For an example of how this could be done currently, I recommend taking a look at the [flutter_bloc_feature](https://github.com/felangel/bloc/blob/511008b7348d043cb8fa49a4c1848304a60f741b/bricks/flutter_bloc_feature/hooks/pre_gen.dart#L21) brick which uses the bloc, cubit, and other bricks internally.

Let me know if that helps 👍

**Comment by SSebigo** [comment]
Doesn't look too complicated, thx @felangel.
