### ISSUE TITLE
feat: confusion about basic workflow -- missing feature?

### ISSUE THREAD

**Issue by RandalSchwartz** [felangel/mason#748]
Not sure if this is a documentation bug, or a missing feature.

So, I write `mason init` then `mason new somebrick --hooks`, and I edit that a bit.

Now I want to test it.  I try `mason make somebrick`.

 Nothing.  Not found.  Stare at the docs for a bit, and come up with `mason add --path newbrick newbrick`.

Then, I can test `mason make newbrick`.  Yeay.

And, it seems to keep tracking my brick as I make changes, so it's not like the "add" command copied anything anywhere.

Am I missing something in the workflow?  Why doesn't making a brick immediately make it testable?  And it's also odd that even if you want to require "mason add", why do I need to say newbrick *twice* in close proximity like that?

**Comment by felangel** [comment]
Hi @RandalSchwartz 👋 
Thanks for opening an issue!

If you want to test your local brick, you can either:
- install it locally (`mason add somebrick --path ./path/to/somebrick`)
  - this will add the brick to your `mason.yaml` file and install
- install it globally (`mason add -g somebrick --path ./path/to/somebrick`)
  - this will install the brick globally on your machine and you can use it in any directory/workspace
  
> Am I missing something in the workflow? Why doesn't making a brick immediately make it testable?

Creating a new brick doesn't immediately install the brick because it would have to make an assumption about whether the brick should be locally or globally installed. 

> And it's also odd that even if you want to require "mason add", why do I need to say newbrick twice in close proximity like that?

`mason add` requires the name of the brick followed by the location of the brick:

`mason add <brick-name> --path <location-of-brick>`

Let me know if that helps!

**Comment by RandalSchwartz** [comment]
> Creating a new brick doesn't immediately install the brick because it would have to make an assumption about whether the brick should be installed locally or globally. Also it would potentially need to generate a new mason.yaml if one didn't already exist (for local use).

But, you're inside the "mason init" directory.  Shouldn't it presume that everything you do with "new" you'll want to test out in that same environment immediately?

It just feels clunky, but you've now confirmed that I'm not missing something in the documentation.  It's just that awkward by design. :)

**Comment by felangel** [comment]
> Shouldn't it presume that everything you do with "new" you'll want to test out in that same environment immediately?

That would make the `new` command more confusing in my opinion because the effects of running the command would vary depending on the context in which the command was run.

**Comment by RandalSchwartz** [comment]
I'm actually happy now that I've understood that once I have added the new brick to the local or global scope, it continues to be watched for changes... I was worried that it would be an "edit... update someehow... test" cycle.  Instead, it's just "edit ... make (and see results)".  That's cool, just wasn't documented that way.  Maybe a separate page on "developing new bricks, what's the process?" to make it less scary and to inform about the automatic watching of the source material.

**Comment by felangel** [comment]
> I'm actually happy now that I've understood that once I have added the new brick to the local or global scope, it continues to be watched for changes... I was worried that it would be an "edit... update someehow... test" cycle. Instead, it's just "edit ... make (and see results)". That's cool, just wasn't documented that way. Maybe a separate page on "developing new bricks, what's the process?" to make it less scary and to inform about the automatic watching of the source material.

Glad to hear that! Yeah happy to update the docs to call attention to the fact that you can iterate in local bricks without having to re-add them 👍

**Comment by felangel** [comment]
Added a new section to the docs covering local brick development:
https://docs.brickhub.dev/brick-development
