### ISSUE TITLE
fix: PowerShell doesn't work with arrow keys during logger prompts

### ISSUE THREAD

**Issue by brennan-smith** [felangel/mason#816]
**Description**

Using any logger command that requires user input with options (ie. `logger.chooseOne` or `logger.chooseAny`) on a PowerShell terminal does not work. 

Note: J and K still move the selector up and down.

**Steps To Reproduce**

1. Create a chooseOne or chooseAny logger with multiple options.
2. Run the command from PowerShell in Windows as an Admin.
3. Notice up/down arrows do not change your selection but j/k do.

**Expected Behavior**

Up and down arrows behave the same as J and K when running in Windows PowerShell.

**Comment by eseidel** [comment]
https://github.com/tj/n/issues/667 looks related.
