### ISSUE TITLE
fix(mason_cli): shell startup time is very slow when using auto completion .

### ISSUE THREAD

**Issue by ebsangam** [felangel/mason#837]
**Description**

Shell startup time is very slow while using auto completion. VS Code reports `Unable to resolve your shell environment` on first start after booting Mac.

**Steps To Reproduce**

1. Use auto completion `[[ -f /Users/sangam/.dart-cli-completion/zsh-config.zsh ]] && . /Users/sangam/.dart-cli-completion/zsh-config.zsh || true`
2. Restart Mac, open VS Code or terminal. First start time very slow.

**Expected Behavior**

Startup time should be fast.

**Screenshots**

**Additional Context**

Removing(commenting) auto completion resolves the issue.

**Comment by ebsangam** [comment]
> If you comment the line `[[ -f /Users/sangam/.dart-cli-completion/zsh-config.zsh ]] && . /Users/sangam/.dart-cli-completion/zsh-config.zsh || true` with `## [[ -f /Users/sangam/.dart-cli-completion/zsh-config.zsh ]] && . /Users/sangam/.dart-cli-completion/zsh-config.zsh || true` does it make it faster?

Yes

**Comment by renancaraujo** [comment]
I think this may be an issue on `https://github.com/VeryGoodOpenSource/cli_completion`. Would you mind transferring this conversation there?

**Comment by ebsangam** [comment]
I faced slow startup today even though auto completion is disabled. I am closing this issue for now.

**Comment by renancaraujo** [comment]
Fantastic, thank you.
