### ISSUE TITLE
fix: Creating a filename with slash for conditional bricks variables

### ISSUE THREAD

**Issue by OldMetalmind** [felangel/mason#850]
**Description**

Creating a file name for a conditional brick variable, with a slash ( aka: forward slash, Solidus, /) is not possible in linux based OSs since it is a reserved character.

**Steps To Reproduce**

1. Use MacOS
2. Run bash `touch {{#createChangelog}}CHANGELOG.md{{/createChangelog}}`;
3. Error `No such file or directory`;

**Expected Behavior**

I should be able to create a conditional brick template file.

**Screenshots**
N/A

**Additional Context**
Maybe we can use a different special caracter for the closing mustache conditional? Given / is reserved.

This is useful when we want to create a conditional for the file name ( https://docs.brickhub.dev/brick-syntax#-conditionals ) however even if we escape the special character forward slash with a backslash, it gives out the error `No such file or directory`.
I also tried to create the file directly through the IDE but without success

None of the following work: 

```bash
touch {{#createChangelog}}CHANGELOG.md{{/createChangelog}}
-> : No such file or directory

touch {{#createChangelog}}CHANGELOG.md{{\/createChangelog}}
-> : No such file or directory

touch \{\{\#createChangelog\}\}CHANGELOG.md\{\{/createChangelog\}\}
-> : No such file or directory

touch "\{\{\#createChangelog\}\}CHANGELOG.md\{\{/createChangelog\}\}"
-> : No such file or directory

**Comment by felangel** [comment]
Glad that helped!

> Maybe we should have a note in the documentation https://docs.brickhub.dev/brick-syntax#-conditionals stating that?

I don’t think it works universally on all platforms/os so I’m hesitant to update the docs to recommend it.

**Comment by felangel** [comment]
Closing for now but feel free to comment with any follow ups and I'm happy to continue the conversation 👍
