### ISSUE TITLE
feat:  Escape <> characters to put list results inside the json template for example: list< class > generate list& lt;class& gt;%

### ISSUE THREAD

**Issue by FelipeRinconVillegas1** [felangel/mason#852]
**Description**

Escape <> characters to put list results inside the json template for example: list< class > generate  list& lt;class& gt;%

**Requirements**

Escape < > characters : 
list < class > = list < class >

**Comment by LukeMoody01** [comment]
Hey @FelipeRinconVillegas1 👋

All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

This way the < and > will be unescaped. Hope that helps!
