### ISSUE TITLE
fix: When a directory inside the __brick__ has no file it is not generated by mason make

### ISSUE THREAD

**Issue by ggouvea-dev** [felangel/mason#86]
**Description**

Just create a new brick, populate the folder `__bricks__` an create a folder but dont place any file inside.
Run mason make $yourBrick

Expected:

I expected that everything inside `__brick__` was  bundled together.

Just for context, I was creating a template for dart gRPC and I would like to include the directory structure within the template. If it is the default behaviour, there's any workaround?

**Comment by felangel** [comment]
Hi @ggouvea-dev 👋
Thanks for opening an issue!

Can you please provide a link to a reproduction sample? I’m not sure I fully understand the issue, thanks! 🙏

**Comment by ggouvea-dev** [comment]
Thanks for the quickly reply.
I just uploaded [this](https://github.com/ggouvea-dev/gh_issue) mason repo.
There you will find the "gh_issue" brick and I also added a generated folder called "reproduction_sample" which is the result of running "mason make gh_issue".

**Comment by felangel** [comment]
Hey @ggouvea-dev I took a look and opened a [pull request](https://github.com/ggouvea-dev/gh_issue/pull/1) with my suggestions. I recommend using a [.gitkeep](https://github.com/ggouvea-dev/gh_issue/pull/1) to indicate that the directory should be created and tracked by source control even though it is empty. I also made some improvements to the template structure and created a .gitignore to avoid tracking the `.mason` directory. Let me know if that helps 👍

**Comment by ggouvea-dev** [comment]
@felangel In fact it will work because the directory will not be empty anymore but I guess it is definitely a good solution since it will also allow the versioning of the generated code from the beginning.
Thanks and keep up with the great work you've been doing with all the packages.
