### ISSUE TITLE
docs: How to debug?

### ISSUE THREAD

**Issue by idc77** [felangel/mason#865]
**Description**

How to print verbose debug output?
I met an error, how do I debug it?

**Requirements**

- [ ] Requirements go here

**Comment by felangel** [comment]
Hi @idc77 👋 
Thanks for opening an issue!

Can you please elaborate? What issue are you facing? Can you share the steps you took as well as the error you're encountering? Thanks!

**Comment by felangel** [comment]
Closing for now since there aren't any actionable steps here. Feel free to provide additional context and I'm happy to revisit this, thanks!
