### ISSUE TITLE
fix: Install bricks from a git repository

### ISSUE THREAD

**Issue by PoloLacoste** [felangel/mason#87]
**Description**

Installing from a git repository is not finding any bricks.

**Steps To Reproduce**

`mason i https://github.com/PoloLacoste/mason_bricks`

**Expected Behavior**

I was expecting mason to install all the bricks described by the `mason.yaml` file inside the repository.

**Result**

```
brick not found at url https://github.com/PoloLacoste/mason_bricks
```

**Comment by felangel** [comment]
Hi @PoloLacoste 👋 
Thanks for opening an issue!

`mason install` requires the path to the specific brick you'd like to install. In your case it could be:

```sh
mason i https://github.com/PoloLacoste/mason_bricks --path bricks/bloc_page
```

Let me know if that helps! 👍

**Comment by PoloLacoste** [comment]
Thanks for your reply @felangel 😄 

Okey that's what I was thinking after some time.

I think this would be a good idea to add a flag to be able to install all bricks when there is a `mason.yaml` fiile detected inside a folder.

For example a flag like `all`.

Example : 

```sh
mason i https://github.com/PoloLacoste/mason_bricks --all
```

**Comment by felangel** [comment]
> Thanks for your reply @felangel 😄
> 
> Okey that's what I was thinking after some time.
> 
> I think this would be a good idea to add a flag to be able to install all bricks when there is a `mason.yaml` file detected inside the source (git or folder).
> 
> For example a flag like `all`.
> 
> Example :
> 
> ```shell
> mason i https://github.com/PoloLacoste/mason_bricks --all
> ```

No problem!

What if the `mason.yaml` contains references to bricks in other repositories? Would you also expect remote bricks to be installed?

**Comment by PoloLacoste** [comment]
> 
> 
> > Thanks for your reply @felangel 😄
> > Okey that's what I was thinking after some time.
> > I think this would be a good idea to add a flag to be able to install all bricks when there is a `mason.yaml` file detected inside the source (git or folder).
> > For example a flag like `all`.
> > Example :
> > ```shell
> > mason i https://github.com/PoloLacoste/mason_bricks --all
> > ```
> 
> No problem!
> 
> What if the `mason.yaml` contains references to bricks in other repositories? Would you also expect remote bricks to be installed?

Just to be safe by default and not to have an "infinite" installation chain without really wanting it, 
I would say no.

But I think a flag can allow it, `--all-remote` for example. 
If you have a better idea I let you choose 😄.

**Comment by felangel** [comment]
@PoloLacoste is there any other CLI that behaves like this? As far as I know `pub` doesn't support this and neither does `npm`. I'd prefer to leave this out in order to keep `mason` as simple as possible while remaining consistent with other similar CLIs. Let me know what you think and thanks again!

**Comment by PoloLacoste** [comment]
@felangel you're right, they are not supporting this.

The way I was thinking it was the following one:

How would you install many bricks ?
For example like 10-20. One by one ?

I guess if there is a `mason.yml` file at the root of the git or folder, all the bricks inside should be installed.

I didn't want to have a chain of doom like inside npm but I guess in the future, bricks coulds depends on other bricks. 
So this is something required I think to install every bricks described inside the `mason.yml` file.

**Comment by felangel** [comment]
> @felangel you're right, they are not supporting this.
> 
> The way I was thinking it was the following one:
> 
> How would you install many bricks ?
> For example like 10-20. One by one ?
> 
> I guess if there is a `mason.yml` file at the root of the git or folder, all the bricks inside should be installed.
> 
> I didn't want to have a chain of doom like inside npm but I guess in the future, bricks coulds depends on other bricks.

Currently it’s very similar to pub. You can use mason get (like pub get) to install all bricks in a mason.yaml but if you want to install bricks globally you specify which ones you’d like to install via mason install (like pub global activate).

**Comment by felangel** [comment]
@PoloLacoste going to close this for now since I want to keep things simple and avoid introducing too many new concepts that people aren't familiar. Hope that's okay with you! I'm happy to revisit this as mason matures a bit more 👍
