### ISSUE TITLE
generating multiple files/folders using Mustache templating

### ISSUE THREAD

**Issue by MerseniBilel** [felangel/mason#876]
There are situations where it would be helpful to generate multiple files/folders based on the same template and data.
For example, suppose I have a JSON file with an array of objects, where each object has a file/folder name property. I want to generate a separate file for each object, using a Mustache template with placeholders for each object's properties.

`example`
```json
{
  "files": [
    {
      "filename": "file1.dart"
      ....
    },
    {
      "filename": "file2.dart"
       ....
    },
    {
      "filename": "file3.dart"
        ....
    },
    {
      "filename": "file4.dart"
      ....
    }
  ]
}
```
`mason output`
```bash
├── file1.dart
├── file2.dart
├── file3.dart
└── file4.dart
```

**Comment by felangel** [comment]
Hi @MerseniBilel 👋 
Thanks for opening an issue!

This is already possible with mason, refer to the [todos brick](https://github.com/felangel/mason/tree/master/bricks/todos) for an example and let me know if you have any follow-up questions, thanks!
