### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by PJPAC** [felangel/mason#887]
**Description**
Creating mason bricks in a dedicated project and applying/adding them to other projects not containing mason but located in the same hard-drive. 

**Requirements**
To reach outside of a project with 
- "mason add my_brick --path ..."
- "mason make my_brick -o ..."
either through the full path "C:/Users/…/" or the relative path ./././etc/./source_or_destination_directory”

**Additional Context**
In a playground folder, I have 2 subfolders, mason_bricks/ and app/ corresponding to 2 different projects. 
  playground
  |--- mason_bricks/
  |--- app/
In any of these subfolders/projects, "mason ls" works, or at least I don’t read any error message in Android Studio's terminal. 
I have set up the bricks in mason_bricks/mason/bricks/ and from mason_bricks/mason/ "mason make …" works fine when the output path is still within the mason_bricks project. 
- From app/, I thought that I could use "mason add my_brick --path ./mason_bricks/mason/" to install the bricks from mason_bricks/mason/ in app/, however I get the following error message "Could not find brick at C:/Users/…/app/mason_bricks/mason". 
- If I am in mason_bricks/mason/, and use “mason make my_brick -o "././”, I would expect mason to output my_brick from mason_bricks/mason/ to app/ ; however, my_brick is installed in mason_bricks/.
- Still in mason_bricks/mason, and using “mason make my_brick -o C:\Users\...\app”, I read “created ..\app\my_brick”, but it corresponds to “mason_bricks/app/my_brick”, i.e. a subfolder app/ has been created in mason_bricks/ instead of targetting the existing playground/app/.
Overall, we are confined within a single project, but it would be neat to shine from a creation/storage mason dedicated project to the projects we develop when both are located on our hard-drive.

**Comment by felangel** [comment]
Hi @PJPAC 👋 
Thanks for opening an issue!

Are you able to share a sample project that reproduces the issue you're facing? It would be much easier to help if I'm able to reproduce the issue locally, thanks! 🙏

**Comment by PJPAC** [comment]
Hi Felix, 
Considering that 2 of the initial issues I faced turned out to work as expected, 
#2 PS C:\src\playground\mason_bricks\mason> mason make verif_as -o ..\..\app\lib 
#3 PS C:\src\playground\mason_bricks\mason> mason make verif_as -o C:\src\playground\app\lib
It is probably not worth pursuing
#1 PS C:\src\playground\app\lib> mason add verif_as --path C:\src\playground\mason_bricks\mason
#2' PS C:\src\playground\mason_bricks\mason> mason make verif_as -o .\.\app\lib
even though I would be curious to understand what I did wrong with the add --path command.

Apologies for having created the post without having more carefully created a step-by-step protocol to be implemented while reproducing the situation. I'll do better if, in the future, I believe to notice something unexpected.
To close my initial request in a clean manner, you will you will find below the step-by-step protocol I have just prepared along with a zip folder containing the playground directory.

[playground.zip](https://github.com/felangel/mason/files/11375019/playground.zip)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

IDE Android Studio
Selected File, New Flutter project
Selected Flutter, Flutter SDK path: C:\src\flutter
New Project	Project name: 	mason_bricks
		Project location: 	C:\src\flutter\playground\mason_bricks
... left preselected Kotlin & Swift
... unticked iOS, Linux, MacOS, Web as they can be added later…
Project format : 	.idea
terminal> dart pub global activate mason_cli had been run elsewhere before
Right click mason_bricks, New directory, mason
Terminal PS C:\src\playground\mason_bricks> cd mason
Terminal> dart pub global activate mason_cli had been run elsewhere before so that 
	 PS C:\src\playground\mason_bricks\mason>mason 
-> works fine.
Terminal PS C:\src\playground\mason_bricks\mason>mason init
-> leads to mason.yaml being created
Right click mason directory, New directory, bricks
Terminal PS C:\src\playground\mason_bricks\mason> cd bricks
Terminal PS C:\src\playground\mason_bricks\mason\bricks> mason new verif_as
Edit mason.yaml
	# brick_name:
  	#  path: bricks/brick_name
	verif_as:
    	   path: bricks/verif_as
PS C:\src\playground\mason_bricks\mason> cd ..
PS C:\src\playground\mason_bricks\mason> mason get
PS C:\src\playground\mason_bricks\mason> mason list
C:\src\playground\mason_bricks\mason
└── verif_as 0.1.0+1 -> C:/src/playground/mason_bricks/mason/bricks/verif_as
PS C:\src\playground\mason_bricks\mason> mason make verif_as -o ../lib
-> leads to HELLO.md being created in the lib directory of the mason_bricks project.

Selected Flutter, Flutter SDK path: C:\src\flutter
New Project	Project name: 		app
		Project location: 	C:\src\flutter\playground\app
... left preselected Kotlin & Swift
... unticked iOS, Linux, MacOS, Web as they can be added later…
Project format : 	.idea
-> creates a 2nd project in the playground directory

#1 : in the terminal of the app project
PS C:\src\playground\app> mason
-> works.
PS C:\src\playground\app> mason init
PS C:\src\playground\app> mason add verif_as --path C:\src\playground\mason_bricks\mason
-> gives : Could not find brick at C:/src/playground/mason_bricks/mason
-> Nothing has been created (consistent with my initial post). I would have expected HELLO.md to be created at the root of the app project. 
PS C:\src\playground\app> cd lib
PS C:\src\playground\app\lib> mason add verif_as --path C:\src\playground\mason_bricks\mason
-> gives : Could not find brick at C:/src/playground/mason_bricks/mason
-> This is consistent with my initial post. Nothing has been created. I would have expected HELLO.md to be created in the lib directory of the app project.

#2 : in the terminal of the mason_brick project
PS C:\src\playground\mason_bricks\mason> mason make verif_as -o .\.\app\lib
? What is your name? (Dash) PascalA
✓ Generated 1 file. (44ms)
  created app\lib\HELLO.md
-> This is consistent with my initial post, as I had understood .\ as a way to go up the structure towards C:\, then the first .\ would have been going to mason_bricks, the second .\ was reaching playground, then \app\lib was entering the app project. However, I misunderstood .\ as the result is that HELLO.md is located in a newly created set of directories C:\src\playground\mason_bricks\mason\app\lib\HELLO.md.

... However...
PS C:\src\playground\mason_bricks\mason> mason make verif_as -o ..\..\app\lib            
? What is your name? (Dash) Myself
✓ Generated 1 file. (46ms)
  created ..\..\app\lib\HELLO.md
-> does create HELLO.md at the expected location. I got confused with .\ and ..\, and mason works probably as expected. 

#3 : in the terminal of the mason_brick project
PS C:\src\playground\mason_bricks\mason> mason make verif_as -o C:\src\playground\app\lib
-> Mason actually works as expected and the present outcome contradicts my initial post. It does lead to HELLO.md being created in the lib directory of the app project... contrary to what I had faced a few days ago when I used projects located deeper in the hard-drive... :/

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Considering that 2 of my initial issues turn out to work as expected, 
#2 PS C:\src\playground\mason_bricks\mason> mason make verif_as -o ..\..\app\lib 
#3 PS C:\src\playground\mason_bricks\mason> mason make verif_as -o C:\src\playground\app\lib
It is probably not worth pursuing 
#1 PS C:\src\playground\app\lib> mason add verif_as --path C:\src\playground\mason_bricks\mason
#2' PS C:\src\playground\mason_bricks\mason> mason make verif_as -o .\.\app\lib
even though I would be curious to understand what I did wrong with the add --path command.
Again, apologies for having created the post without having more carefully created a step-by-step protocol to be implemented while reproducing the situation.

**Comment by felangel** [comment]
Hi @PJPAC 👋 
Mason add `--path` needs to have a path to the directory containing the `brick.yaml` for the target brick. I'm guessing you need to adjust your command to:

```
mason add verif_as --path C:\src\playground\mason_bricks\mason\verif_as
```

If you're still having trouble, please provide a link to a minimal reproduction sample and I'm happy to take a closer look. Closing for now, cheers!
