### ISSUE TITLE
feat: promote to stable?

### ISSUE THREAD

**Issue by feinstein** [felangel/mason#891]
I am considering adopting this library, but I can see it's in dev version for almost 1 year and a half, which makes me think: What's missing for the library to be upgraded to a stable version release?

**Comment by felangel** [comment]
Hi @feinstein 👋 
Thanks for opening an issue!

I'm currently working on #215 at which point I plan to publish a stable release. I don't anticipate many breaking changes so I consider it fairly low risk to adopt at the moment but I'm hoping to have a stable release in the next month.

**Comment by feinstein** [comment]
Awesome, thanks!
