### ISSUE TITLE
feat: Allow color theming

### ISSUE THREAD

**Issue by matthew-carroll** [felangel/mason#904]
**Description**

I'd like to change the colors for some messages in the logger. This is partially for branding purposes, and partially to draw extra attention to areas, using colors that aren't currently assigned to the various logger methods.

**Comment by felangel** [comment]
Hi @matthew-carroll

You can currently use the built-in colors like yellow.wrap(‘…’) etc with the various logger APIs. Do you prefer to have a theme property that you can specify when creating a logger instance? Just want to make sure I understand the feature request, thanks!

**Comment by matthew-carroll** [comment]
A couple things: First, I would suggest elevating some documentation about how to do that. I poked around wherever I could and I didn't notice that wrap behavior. I didn't know that was possible, or intended.

Second, I would prefer something that's easier to repeat. Imagine that I have a special header message that I output for every phase of a generation pipeline. I want every header to be yellow. Either, I need to remember to add that wrap at each location, or I have to do something like add an extension method on the logger. That's not terrible, but it is tedious, and it feels like something that should configurable within the logger.

Instead, a logger could take a theme, which maps every level/message type to a color. Not that I recommend messing with all the colors, but each developer might have any number of reasons to adjust any one or two colors from the standard. Additionally, there could be a global default theme for all loggers, which itself could be replaceable with your desired theme, so that you don't need to keep passing the same theme to each new logger that you create.

**Comment by felangel** [comment]
@matthew-carroll since we're not just limited to `color`, what are your thoughts on the following API:

```dart
final logger = Logger();

// A custom [LogStyle] which outputs bold, light magenta messages.
String? customStyle(String? message) => styleBold.wrap(lightMagenta.wrap(message));

logger.info('Hello World', style: customStyle);
```

I believe this would give us the flexibility of fully customizing the style of the message while still addressing the original ask but would love to hear your thoughts.

**Comment by matthew-carroll** [comment]
I think that technically that would solve the problem. I would still probably work in some kind of optional theme or style inheritance so that you can customize all styles form a single place, when appropriate.

Can you let me know the history behind this `wrap()` concept? At first glance, it feels like a strange way to work with styles...

**Comment by felangel** [comment]
> I think that technically that would solve the problem. I would still probably work in some kind of optional theme or style inheritance so that you can customize all styles form a single place, when appropriate.
> 
> Can you let me know the history behind this `wrap()` concept? At first glance, it feels like a strange way to work with styles...

It comes from `package:io` iirc but I'm also totally open to revamping the API since I agree it's not the most ergonomic way to compose styles.

Perhaps something more like Flutter's `TextStyle`?

```dart
final customStyle = LogStyle(color: LogColors.lightMagenta, fontWeight: LogFontWeight.bold);
logger.info('Hello World', style: customStyle);
```

**Comment by matthew-carroll** [comment]
Are there situations where developers style pieces of a single message string?

**Comment by felangel** [comment]
> Are there situations where developers style pieces of a single message string?

Yeah we should still allow for inline styles imo. A good example is `mason_cli`'s prompt:

```dart
final prompt = '${styleBold.wrap(lightGreen.wrap('?'))} ${properties.prompt ?? variable}';
final response = logger.prompt(prompt, defaultValue: properties.defaultValue);
```

**Comment by matthew-carroll** [comment]
In that case, what do you think about integrating `attributed_text`? The current API might not be perfect for mason_logger, but we could probably add some shorthand construction options.

`attributed_text` is the foundation for all styled text in `super_editor`.

https://pub.dev/packages/attributed_text

**Comment by matthew-carroll** [comment]
You might also consider adding something like inline Markdown support to avoid the verbosity of something like `styleBold.wrap(...)`.

**Comment by felangel** [comment]
I'll look closer at `attributed_text` but I believe #909 should satisfy the requirements without introducing breaking changes. Let me know what you think, thanks!

**Comment by Luckey-Elijah** [comment]
To add: I would prefer `mason_logger` _not_  to infer markdown-like syntax unless specified. String can often be dynamically created that include a lot of `_` and `*` which would create undesired behavior in many of my projects

So users should be explicit with markdown-like syntax in someway:

```dart
logger.info('_no markdown_');
logger.info('_with markdown_'.md); // extension method
logger.info(md('_with markdown_')); // helper method
logger.info('_with markdown_',  style: myStyleWithMarkdownEnabled); // via "new" style option
```

Markdown would be neat otherwise 👍🏻 

PS Maybe a new issue to track the idea of markdown-like syntax.

**Comment by felangel** [comment]
> #909 generally LGTM. Should there be a way to set a default theme, such that all loggers created from that point internally use that default theme? In practice, I don't know if larger projects tend to instantiate a lot of different loggers. If they do, then repeating the same theme argument over and over might get tedious. Aside from that possible concern, I think the proposal works for my use-case.

I figured if you wanted to avoid having to pass the same theme argument over and over you could extend `Logger` and override the `theme` like:

```dart
class CustomLogTheme extends LogTheme {
  //... 
}

class MyLogger extends Logger {
  MyLogger({super.level, super.progressOptions}) : super(theme: CustomLogTheme());
}
```
