### ISSUE TITLE
refactor: Create backend and frontend for mason generator for better modularity and future enhancements

### ISSUE THREAD

**Issue by definitelyokay** [felangel/mason#91]
#### Create backend and frontend for mason generator for better modularity and future enhancements

The following is a little bit of brain-storming around updating mason's architecture given that mason may eventually implement mustache partials (basically include files—see #90) and output transformers at some point.

The mason generator APIs would likely benefit from an additional layer of abstraction. Code could be refactored into a front end layer and a backend layer, each with their own responsibilities:

#### Frontend:
- Dispatch broad, abstract commands from the generator API to the relevant subsystems.
- Handles the abstract notion of files, bricks, and bundles to perform file access, template rendering, and output generation.
- Communicate with the backend to fetch/read/write across the file system/network/inter-process-communication/callbacks/etc as needed without being tied to any particular implementation.

This frontend is not to meant to be confused with the part of mason that handles CLI input—the CLI code could be a platform-specific front end for the front end, and would simply call into this code to perform requests, making it just another mason client. 😛

#### Backend:
- Dispatch requests from the front end for fetching files, reading directories, writing files, creating directories, scanning directory contents, etc to one or more adapters which conform to a common input/output interface to perform these functions in the specified environment.

Depending on how much modularity is desired, mason could potentially be split into several subsystems or packages:

- `mason_cli` — responsible for collecting console input and dispatching to mason engine.
- `mason_generator` — contains the front end and back end.
- `mason_environment` — a single interface which is consumed by the `mason_generator` for all filesystem-type operations.
- One package for each environment interface implementation. These could take on the form of the following, if desired: `mason_github`, `mason_filesystem`, `mason_filesystem_windows`, `mason_streams`, etc.

**Requirements**

- [ ] There is no drop in test coverage.

**Comment by felangel** [comment]
Thanks so much for opening the issue! I think this is a create idea and just had a few minor adjustments that I want to get your  thoughts on 👇 

![mason_architecture](https://user-images.githubusercontent.com/8855632/123453418-26ab1b00-d5a5-11eb-9802-9fd6ab589f18.png)

**Comment by felangel** [comment]
Closing this for now since we've modularized quite a bit since this issue was created and I propose to apply additional modularization as needed.
