### ISSUE TITLE
feat: chooseOne with one item should just return that item

### ISSUE THREAD

**Issue by eseidel** [felangel/mason#913]
Right now chooseOne prompts even if it only has one item.

Maybe that's works as intended?

I originally assumed it would just return that one. 🤷

**Comment by felangel** [comment]
Hmm can you provide a bit more context? Why use `chooseOne` with only a single item?

**Comment by eseidel** [comment]
Sorry, I was pulling data from a server and not knowing how many responses there would be.  e.g.
https://github.com/eseidel/space_traders/blob/3f374f7b052d4818ae5efa4e913b9c5ffdb0c972/packages/space_traders_cli/bin/show_market.dart#L20

I think choseOne's existing behavior is fine.  Closing.
