### ISSUE TITLE
fix: Conditionally generate files

### ISSUE THREAD

**Issue by SebastianPilarz** [felangel/mason#963]
**Description**

Hi, just started using this great tool, but one thing is not clear to me. In the docs (https://docs.brickhub.dev/brick-syntax/#-conditionals) it's mentioned that it's possible to conditionally generate files. I'm not sure if it's a bug or I'm missing something but since "/" is not allowed in file names on Unix-like systems, how am I supposed to create the following directory structure:
<pre>
├── __brick__
│   └── {{#createChangelog}}CHANGELOG.md{{/createChangelog}}
                                          ^
                                          Here is the problem
</pre>

**Steps To Reproduce**

Just try to create a file with "/" in the name on Linux or another *nix OS.

**Expected Behavior**

Be able to conditionally generate the CHANGELOG.md if the createChangelog variable is set to true, using the above method.

**Screenshots**

Of course I'm not able to create this file

![mason_conditional_file](https://github.com/felangel/mason/assets/114884987/8d7bee55-8a5a-42ec-b862-f60a0503f199)

![mason_conditional_file_terminal](https://github.com/felangel/mason/assets/114884987/7a50bb5e-236f-4c01-b71e-099270634c6e)

**Additional Context**

I'm running Ubuntu 20.04.6 LTS amd64

**Comment by felangel** [comment]
Hi @SebastianPilarz 👋 
Thanks for opening an issue!

I believe this is a duplicate of https://github.com/felangel/mason/issues/751 and https://github.com/felangel/mason/issues/36.  You can also refer to the following example brick: https://github.com/felangel/mason/tree/master/bricks/plugin/__brick__

Let me know if that helps 👍

**Comment by SebastianPilarz** [comment]
Yeah, got it. Guess I rushed it a bit with this report :)
Anyway taking into account I wasn't the only one who had doubts about it, I think the example directory structure in the documentation is a little bit misleading for some people because it combines two different approaches of presenting it: one in graphical format and the other using the '/'. I believe the docs could be more consistent here.
If it were to be a graphical representation it would be more like this:

to generate a single file (here CHANGELOG.md)
<pre>
├── __brick__
│   └── {{#createChangelog}}CHANGELOG.md{{
│       └── createChangelog}}   <── the actual file
</pre>

to generate a directory with some files (here .vscode with few json files)
<pre>
├── __brick__
│   └── {{#createVsCodeFiles}}.vscode{{
│       └── createVsCodeFiles}}
│           ├── launch.json
│           ├── tasks.json
│           └── settings.json
</pre>

Guess it would be helpful for new users if at least one of the above examples were in the docs.
Thanks for your time, the problem is solved :+1:
