### ISSUE TITLE
chore: How to generate files from array

### ISSUE THREAD

**Issue by anthonycuervo23** [felangel/mason#975]
In the event that you want to ask the user which environments he wants to support for the project from a list of determined values, how can I then generate the respective main_dev.dart, main_prod.dart, etc... according to the user's selection?
  
  environments:
    type: array
    description: The environments to generate.
    prompt: Which environments do you want to generate?
    default:
      - stage
      - prod
    values:
      - dev
      - stage
      - prod

**Comment by felangel** [comment]
Hi @anthonycuervo23 👋 
Thanks for opening an issue!

You can use the same loop syntax in the file name -- check out the [todos example](https://github.com/felangel/mason/tree/master/bricks/todos) for reference. Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with any questions and I'm happy to continue the conversation 👍
