### ISSUE TITLE
feat: Infinite promt until stopped by user

### ISSUE THREAD

**Issue by erlangparasu** [felangel/mason#986]
**Description**

Infinite promt until stopped by user. Store the answers as `List<String>`.

**Requirements**

- [ ] Store each answer line by append each line to a `List<String>`
- [ ] If user enter empty string, stop prompting the question, show next question/prompt.

For example: Question prompt
`Please input json properties name`

:D

**Comment by felangel** [comment]
Hi @erlangparasu 👋
I’m just wrapping this up via #976 should be available this weekend 👍

**Comment by erlangparasu** [comment]
@felangel Thanks! :D
